### ISSUE TITLE
Generating csharp on latest version fails

### ISSUE THREAD

**Issue by aanufriyev** [Azure/autorest.csharp#1080]
Today updated AutoRest to try generation with v3.

Outcome of this was:
```
E:\> autorest --input-file=api-docs.json --csharp
AutoRest code generation utility [cli version: 3.1.2; node: v14.16.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.1.0.
   Loading AutoRest core      'C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist' (3.1.3)
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210310.1)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.17.2->4.17.2)
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Process() cancelled due to failure
```

Debug output
```
VERBOSE [2.01 s]: > Including configuration file 'file:///C:/Users/aanuf/.autorest/@autorest_modelerfour@4.17.2/node_modules/@autorest/modelerfour/readme.md'
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Process() cancelled due to exception : [Exception] AutoRest extension '@autorest/csharp' terminated. / Error: [Exception] AutoRest extension '@autorest/csharp' terminated.
    at C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2028:17
    at CallbackList.invoke (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100362:39)
    at Emitter.fire (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100426:36)
    at closeHandler (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101003:26)
    at CallbackList.invoke (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100362:39)
    at Emitter.fire (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100426:36)
    at StreamMessageReader.exports.modules.../../../common/temp/node_modules/.pnpm/vscode-jsonrpc@3.6.2/node_modules/vscode-jsonrpc/lib/messageReader.js.AbstractMessageReader.fireClose (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101797:27)
    at Socket.<anonymous> (C:\Users\aanuf\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101850:62)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```
Cleaned old netcore SDKs just in case.
Also noticed strange behavior - during first run `node_modules` is created in `C:\Users\aanuf` and to overcome this I had to manually copy it to `C:\Users\aanuf\.autorest\@autorest_csharp@3.0.0-beta.20210310.1`

Any ideas how to recover from this state? using --legacy or --v2 switch also results in unwanted behavior but this is probably not in scope of this issue.

EDIT:
`dotnet --list-sdks` 

```
E:\> dotnet --list-sdks
2.1.401 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.112 [C:\Program Files\dotnet\sdk]
3.1.407 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
```

**Comment by chamons** [comment]
Sorry for the delay in response - @aanufriyev could you please list the version of node you have installed?

We've seen some strange behavior on older nodes that sounds like:

```
 Also noticed strange behavior - during first run node_modules is created in C:\Users\aanuf and to overcome this I had to manually copy it to C:\Users\aanuf\.autorest\@autorest_csharp@3.0.0-beta.20210310.1
```
