### ISSUE TITLE
Generator crashes on updated ACR swagger file

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1083]
On this input file: https://github.com/Azure/azure-sdk-for-js/blob/8642ffaf0354502860d31b4b07a506299cbed3f4/sdk/containerregistry/container-registry/swagger/containerregistry.json

The C# code generator fails with the error below.  The JS generator succeeds on the same swagger file.

Error:
```
  FATAL: System.Collections.Generic.KeyNotFoundException: The given key 'reference' was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at AutoRest.CSharp.Output.Models.RestClient.GetPathSegments(String httpRequestUri, Dictionary`2 parameters, Boolean isRaw)+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 462
     at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.SparseArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.SparseArrayBuilder1.ReserveOrAdd(IEnumerable1 items)
     at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
     at AutoRest.CSharp.Output.Models.RestClient.BuildMethod(Operation operation, HttpRequest httpRequest, ICollection`1 requestParameters, ResponseHeaderGroupType responseHeaderModel) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 353
     at AutoRest.CSharp.Output.Models.RestClient.EnsureNormalMethods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 116
     at AutoRest.CSharp.Output.Models.RestClient.GetOperationMethod(ServiceRequest request) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 551
     at AutoRest.CSharp.Output.Models.RestClient.BuildAllMethods()+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 77
     at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.RestClient.get_Methods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 66
     at AutoRest.CSharp.Generation.Writers.RestClientWriter.WriteClient(CodeWriter writer, RestClient restClient) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\RestClientWriter.cs:line 42
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 64
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 152
     at AutoRest.CSharp.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\PluginProcessor.cs:line 36
EXEC : error : Plugin csharpgen reported failure. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
```

Full generator output:

```
PS C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src> dotnet build /t:GenerateCode
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  AutoRest code generation utility [cli version: 3.0.6339; node: v12.18.3, max-memory: 2048 MB]
  (C) 2018 Microsoft Corporation.
  https://aka.ms/autorest
     Loading AutoRest core      'C:\Users\annelo\.autorest\@autorest_core@3.0.6371\node_modules\@autorest\core\dist' (3.0.6371)
     Loading local AutoRest extension '@autorest/csharp' (C:/Users/annelo/.nuget/packages/microsoft.azure.autorest.csharp/3.0.0-beta.20210302.2/buildMultiTargeting/../tools/netcoreapp3.0/any/)
     Loading AutoRest extension '@autorest/modelerfour' (4.17.0->4.17.0)

EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributesBase' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrManifests' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrErrors' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'RepositoryTags' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ImageSignature' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'JWK' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'JWKHeader' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'History' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'Repositories' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'DeletedRepository' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrErrorInfo' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'FsLayer' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'Descriptor' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ChangeableAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributes_tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes_manifest_references' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes_manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestChangeableAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestWrapper' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestListAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'Platform' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'V2Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'OCIManifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'OCIIndex' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/SchemaMissingType): The schema 'V1Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

EXEC : warning (Modeler/MissingType): The schema 'paths┬╖v9pjtw┬╖v2-name-manifests-reference┬╖put┬╖responses┬╖201┬╖content┬╖application-json┬╖schema' has no type or format information whatsoever. Location: [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
     https://github.com/Azure/azure-sdk-for-js/blob/8642ffaf0354502860d31b4b07a506299cbed3f4/sdk/containerregistry/container-registry/swagger/containerregistry.json#/components/schemas/paths┬╖v9pjtw┬╖v2-name-manifests-reference┬╖put┬╖responses┬╖201┬╖content┬╖application-json┬╖schema
  INFORMATION: Options {"input":["prechecker"],"always-create-content-type-parameter":true,"flatten-models":true,"flatten-payloads":true,"group-parameters":true,"always-create-accept-parameter":true,"naming":{"override":{"cmyk":"CMYK","$host":"$host"}}}
  INFORMATION: Accept-param true
  INFORMATION: Options {"input":["prechecker"],"always-create-content-type-parameter":true,"flatten-models":true,"flatten-payloads":true,"group-parameters":true,"always-create-accept-parameter":true,"naming":{"override":{"cmyk":"CMYK","$host":"$host"}}}
  INFORMATION: Accept-param true
  FATAL: System.Collections.Generic.KeyNotFoundException: The given key 'reference' was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at AutoRest.CSharp.Output.Models.RestClient.GetPathSegments(String httpRequestUri, Dictionary`2 parameters, Boolean isRaw)+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 462
     at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.SparseArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.SparseArrayBuilder1.ReserveOrAdd(IEnumerable1 items)
     at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
     at AutoRest.CSharp.Output.Models.RestClient.BuildMethod(Operation operation, HttpRequest httpRequest, ICollection`1 requestParameters, ResponseHeaderGroupType responseHeaderModel) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 353
     at AutoRest.CSharp.Output.Models.RestClient.EnsureNormalMethods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 116
     at AutoRest.CSharp.Output.Models.RestClient.GetOperationMethod(ServiceRequest request) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 551
     at AutoRest.CSharp.Output.Models.RestClient.BuildAllMethods()+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 77
     at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.RestClient.get_Methods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\RestClient.cs:line 66
     at AutoRest.CSharp.Generation.Writers.RestClientWriter.WriteClient(CodeWriter writer, RestClient restClient) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\RestClientWriter.cs:line 42
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 64
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 152
     at AutoRest.CSharp.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\PluginProcessor.cs:line 36
EXEC : error : Plugin csharpgen reported failure. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\Microsoft.Azure.AutoRest.CSharp.targets(32,5): error MSB3073: The command "npx autorest@3.0.6339 --skip-csproj --skip-upgrade-check --version=3.0.6371 C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src/autorest.md  --use=C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\../tools/netcoreapp3.0/any/ --output-folder=C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src/Generated --clear-output-folder=true --namespace=Azure.Containers.ContainerRegistry --shared-source-folders="C:\src\azure-sdk-for-net\eng\/../sdk/core/Azure.Core/src/Shared/;C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\../content/Generator.Shared/"" exited with code 1. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]

Build FAILED.

EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributesBase' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrManifests' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrErrors' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'RepositoryTags' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ImageSignature' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'JWK' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'JWKHeader' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'History' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'Repositories' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'DeletedRepository' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'AcrErrorInfo' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'FsLayer' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'Descriptor' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ChangeableAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'TagAttributes_tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes_manifest_references' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestAttributes_manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestChangeableAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestWrapper' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'ManifestListAttributes' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'Platform' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'V2Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'OCIManifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'OCIIndex' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/SchemaMissingType): The schema 'V1Manifest' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object' [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : warning (Modeler/MissingType): The schema 'paths┬╖v9pjtw┬╖v2-name-manifests-reference┬╖put┬╖responses┬╖201┬╖content┬╖application-json┬╖schema' has no type or format information whatsoever. Location: [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
EXEC : error : Plugin csharpgen reported failure. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\Microsoft.Azure.AutoRest.CSharp.targets(32,5): error MSB3073: The command "npx autorest@3.0.6339 --skip-csproj --skip-upgrade-check --version=3.0.6371 C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src/autorest.md  --use=C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\../tools/netcoreapp3.0/any/ --output-folder=C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src/Generated --clear-output-folder=true --namespace=Azure.Containers.ContainerRegistry --shared-source-folders="C:\src\azure-sdk-for-net\eng\/../sdk/core/Azure.Core/src/Shared/;C:\Users\annelo\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210302.2\buildMultiTargeting\../content/Generator.Shared/"" exited with code 1. [C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Azure.Containers.ContainerRegistry.csproj]
    32 Warning(s)
    2 Error(s)

Time Elapsed 00:00:11.06
PS C:\src\azure-sdk-for-net\sdk\containerregistry\Azure.Containers.ContainerRegistry\src>
```

**Comment by annelo-msft** [comment]
@chamons FYI

**Comment by chamons** [comment]
As noted in https://github.com/Azure/autorest/issues/3991 this ended up be a swagger issues. I am looking at improving the error reporting though.
