### ISSUE TITLE
GetAwaiter.GetResult vs Task.Factory.StartNew

### ISSUE THREAD

**Issue by mdzieg** [Azure/autorest.csharp#1091]
I ran into issue with generated client for .NET Framework.
I used to stick with what my VisualStudio was using under the hoods - one of older autorest versions.
It generated *Extensions.cs file with sync methods like this:

```
            public static IList<Country> GetCountriesWithRegions(this IDRRFQ operations)
            {
                return Task.Factory.StartNew(s => ((IDRRFQ)s).GetCountriesWithRegionsAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }
```

Recently I changed my approach and started using autorest directly. New version generates *.Extensions.cs this way:

```
            public static IList<Country> GetCountriesWithRegions(this IDRRFQ operations)
            {
                return operations.GetCountriesWithRegionsAsync().GetAwaiter().GetResult();
            }
```

We then noticed issues during runtime. Randomly we had ThreadAborted exceptions. Sample stack trace:

```
Thread was being aborted.
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ***Extensions.GetCountriesWithRegions(IDRRFQ operations)
```

I found the issue to be connected with GetAwaiter().GetResult() code.

I have the following versions:
Type       Extension Name                           Version
 core       @autorest/core                           3.0.6320
 core       @microsoft.azure/autorest-core           2.0.4417
 extension  @microsoft.azure/autorest.csharp         2.3.90
 extension  @microsoft.azure/autorest.modeler        2.3.55

My workaround for the moment is to get back to VS Add->REST API Client.

**Comment by mdzieg** [comment]
@pakrym v3 version generates code the same way

autorest/csharp                         3.0.0-beta.20210406.5beta.20210406.5

`return operations.GetCountriesWithRegionsAsync().GetAwaiter().GetResult();`

**Comment by pakrym** [comment]
Can you please include a larger snippet of code?

**Comment by mdzieg** [comment]
I am generating using autorest command with this .md file:

```
# Services.Lead 

This file contains the configuration for generating Services.Lead API from the OpenAPI specification.

> see https://aka.ms/autorest

` ` `json
{
"input-file": "./swagger.json",
"csharp": true,
"namespace": "Services.Clients.Lead",
"output-folder": ".",
"add-credentials": true
}
` ` `
```

The problem is how sync methods are generated based on async counterparts. It can be any operation.

```
/// <summary>
            /// Returns list of supported countries with regions
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<Country> GetCountriesWithRegions(this IDRRFQ operations)
            {
                return operations.GetCountriesWithRegionsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns list of supported countries with regions
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Country>> GetCountriesWithRegionsAsync(this IDRRFQ operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCountriesWithRegionsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }
```


I found another solution which is similar to what was generated in older versions. I am using AsyncHelper class and I call directly async method avoiding to use that faulty .GetAwaiter().GetResult(); Async programming is not my forte. Maybe this works just fine on netcore/net5+, but on net4.8 we had those thread aborted exceptions being thrown.

Code of AsyncHelper is coming from internal framework code and is similar to what was generated in older versions:
```
    public static class AsyncHelper
    {
        private static readonly TaskFactory TaskFactory = new
            TaskFactory(CancellationToken.None,
                TaskCreationOptions.None,
                TaskContinuationOptions.None,
                TaskScheduler.Default);

        public static TResult RunSync<TResult>(Func<Task<TResult>> func)
            => TaskFactory
                .StartNew(func)
                .Unwrap()
                .GetAwaiter()
                .GetResult();

        public static void RunSync(Func<Task> func)
            => TaskFactory
                .StartNew(func)
                .Unwrap()
                .GetAwaiter()
                .GetResult();
    }
```

If this indeed is just faulty on .net4.8 maybe additional parameter for generator could be added?
My current invocation when code is not asynchronous:

```
AsyncHelper.RunSync(() => client.DRRFQ.XXXXAsync(request));
```

For async methods everything works just fine.

**Comment by chamons** [comment]
After reviewing this issue, it sounds like you have at least a partial solution using TaskFactory.
 
The V2 generator has design decisions that make resolving this issue difficult without a rewrite (as we did in feature/v3).
 
The V2 generator is only getting critical bug fixes, and this does not meet that bar.
 
If in the future you've migrated to the V3 generator (feature/v3) and are seeing this please consider opening a new issue with details.

Thanks!

**Comment by mdzieg** [comment]
v3 version generates code the same way

autorest/csharp 3.0.0-beta.20210406.5beta.20210406.5

return operations.GetCountriesWithRegionsAsync().GetAwaiter().GetResult();

**Comment by chamons** [comment]
Reopening for review.

**Comment by AlexanderSher** [comment]
@mdzieg , can you please clarify couple of things about the issue:
- When you call `GetCountriesWithRegions` directly, is it called from UI thread, unit-test thread or random background thread?
- What kind of application do you have? Is it a WPF client app, an ASP.NET Core, or something else?

Thank you!

**Comment by mdzieg** [comment]
@AlexanderSher  sure. It is ASP.NET 4.8 app build on Sitefinity CMS. It has to be synchronous because of CMS limitations.

Application is build on Sitefinity. So it may not be the thread that is serving the request originally as the code is in so called widget (it is still MVC but not sure 100% on how it is implemented under the hoods). I can investigate more when I am back to work in a few days. I can give more details on how this is called in the Sitefinity engine as it indeed may be the difference that does not play nice with the generated code.

Other services were using async methods of the API and I did not test them with sync version.
