### ISSUE TITLE
FATAL: Internal error in AutoRest.CSharp - Unhandled promise rejection - file attached

### ISSUE THREAD

**Issue by davidfordaus** [Azure/autorest.csharp#1099]
Full exception and Swagger file is attached

Minor bug: "is a bit ambigious." is mis-spelt

FATAL: YamlDotNet.Core.YamlException: (Line: 6281, Col: 37, Idx: 186430) - (Line: 6281, Col: 37, Idx: 186430): Exception during deserialization
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)

**Comment by davidfordaus** [comment]
[fail.txt](https://github.com/Azure/autorest.csharp/files/6214925/fail.txt)
[file.err.txt](https://github.com/Azure/autorest.csharp/files/6214927/file.err.txt)
[3E_Public_API.swagger.json.txt](https://github.com/Azure/autorest.csharp/files/6214929/3E_Public_API.swagger.json.txt)

**Comment by davidfordaus** [comment]
Crickets ?...
