### ISSUE TITLE
FATAL Internal error: Could not set ResourceType for operations group Operations

### ISSUE THREAD

**Issue by ctaggart** [Azure/autorest.csharp#1264]
From `PS C:\Users\cataggar\io\azure-rest-api-specs>` I ran:
``` ps1
$csharpSdksFolder=(get-item $pwd).parent.fullname + "\azure-sdk-for-net\sdk"

autorest --csharp --azure-arm=true --csharp-sdks-folder=$csharpSdksFolder --reflect-api-versions --tag=package-2020-03-20 specification/vmware/resource-manager/readme.md
```

And ended up with this error:
```
FATAL: Internal error in AutoRest.CSharp
   Please file an issue at https://github.com/Azure/autorest.csharp/issues/new.
   Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

Exception: Could not set ResourceType for operations group Operations
                                            Please try setting this value for this operations in the readme.md for this swagger in the operation-group-mapping section
   at AutoRest.CSharp.Mgmt.Decorator.ResourceTypeBuilder.ConstructOperationResourceType(OperationGroup operationsGroup) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\ResourceTypeBuilder.cs:line 44
   at AutoRest.CSharp.Mgmt.Decorator.ResourceTypeBuilder.ResourceType(OperationGroup operationsGroup, MgmtConfiguration config) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\ResourceTypeBuilder.cs:line 29
   at AutoRest.CSharp.Mgmt.AutoRest.MgmtOutputLibrary.DecorateOperationGroup() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtOutputLibrary.cs:line 401
   at AutoRest.CSharp.Mgmt.AutoRest.MgmtOutputLibrary..ctor(CodeModel codeModel, BuildContext`1 context) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtOutputLibrary.cs:line 51
   at AutoRest.CSharp.Output.Models.Types.BuildContext`1..ctor(CodeModel codeModel, Configuration configuration, SourceInputModel sourceInputModel) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\BuildContextOfT.cs:line 28
   at AutoRest.CSharp.AutoRest.Plugins.MgmtTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtTarget.cs:line 19
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 50
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
[8.96 s] Generation Complete
```

[generated.zip](https://github.com/Azure/autorest.csharp/files/6523747/generated.zip)

**Comment by chamons** [comment]
I am able to reproduce this. 

If you read the error message closely, you'll see:

```
Unhandled exception. System.ArgumentException: Could not set ResourceType for operations group Operations
                                            Please try setting this value for this operations in the readme.md for this swagger in the operation-group-mapping section
```

This is because the ARM mode (--azure-arm) requires attributes for their organization.

I don't believe this is a bug, but I'll let @m-nash confirm for sure.

I've filed https://github.com/Azure/autorest.csharp/issues/1270 to improve the UX in seeing this error.

**Comment by ctaggart** [comment]
> Try fixing up the configuration and report back.

@chamons, can you elaborate? What configuration are you talking about?

**Comment by chamons** [comment]
There are a number of ARM specific attributes, as you can see in this sample:

https://github.com/Azure/autorest.csharp/blob/2e787c959745c00fdff5e97e7066cf05b9357b0d/samples/Azure.ResourceManager.MachineLearning/readme.md

My understanding is that this is crashing as you are lacking some required ones. 

I unfortunately have very limited knowledge of the management side of the house, so i'm unable to give you advice on how to correct your configuration.

I'll raise this to my management peers for response.

**Comment by chamons** [comment]
The generator currently feature/v3 is in the middle of a rewrite and not yet stable.

Azure-sdk-for-net is ["pinned"](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Directory.Build.Common.props#L6) to 3.0.0-beta.20210504.1 version, and I would suggest using it for now. 

Please try that and report back.

**Comment by ctaggart** [comment]
Yes, that specific version did work.
```
autorest --csharp --use=@autorest/csharp@3.0.0-beta.20210504.1 --azure-arm=true --csharp-sdks-folder=$csharpSdksFolder --reflect-api-versions --tag=package-2020-03-20 specification/vmware/resource-manager/readme.md
```
https://www.npmjs.com/package/@autorest/csharp
