### ISSUE TITLE
Exception: Get operation is missing for AmlUserFeature resource

### ISSUE THREAD

**Issue by isra-fel** [Azure/autorest.csharp#1278]
**Describe the issue or request**
**Workspace feature** ([swagger](https://github.com/AME-Redmond/azure-sdk-for-net/blob/yeming/ml/sdk/machinelearningservices/Azure.ResourceManager.MachineLearningServices/src/machineLearningServices.json#L262)) is a special resource in MachineLearningServices RP that it only supports List but no Get.
I got an error "Get operation is missing" when generating the [Resource]Operations class using latest C# generator (v3.0.0-beta.20210526.3) in https://github.com/Azure/azure-sdk-for-net/pull/21321

**Describe your ideas for solutions**
I got 2 ideas how this could be solved
- We do not generate it as resource, but as additional operations to its parent resource (by marking it as **NonResource** in readme and assign a correct parent to it. This is what I am doing)
- The reason why there's an exception thrown when not Get is found is that [Resource]Operations **must** override Get() method inherited from base. We can simply remove Get() from base class and let each [Resource]Operations decide if there's a Get(), just [like what we did](https://github.com/Azure/azure-sdk-for-net/pull/20684) to CreateOrUpdate() in [Resource]Containers.

### Stacktrace

```
  Exception: Get operation is missing for AmlUserFeature resource.
     at AutoRest.CSharp.Mgmt.Generation.ResourceOperationWriter.WriteClient(CodeWriter writer, ResourceOperation resourceOperation, BuildContext`1 context) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Generation\ResourceOperationWriter.cs:line 67
     at AutoRest.CSharp.AutoRest.Plugins.MgmtTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtTarget.cs:line 52
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 50
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
```

**Comment by isra-fel** [comment]
+ @ShivangiReja  @m-nash  @allenjzhang

**Comment by isra-fel** [comment]
Talked w/ Micheal today, conclusions are:
- Generally if a resource has no GET operation, it should inherit `OperationsBase` rather than `ResourceOperationsBase`
  - That part seems missing in `ResourceOperationWriter`
- For this specific case, "workspace features" is pure data, it has no operation on it, we prefer to model it as non-resource and put the LIST operation in parent resource (workspace)

Closing the issue.
