### ISSUE TITLE
[LLC] Crash when parameter with x-ms-parameter-grouping/x-ms-parameter-location in unknown conditionals

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1316]
When generating [this](https://gist.github.com/chamons/22583e4de4aa885e1ea75971471c90b4) swagger with LLC enabled I get:

```
  FATAL: Internal error in AutoRest.CSharp
     Please file an issue at https://github.com/Azure/autorest.csharp/issues/new.
     Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

  Exception: Not implemented type
     at AutoRest.CSharp.Generation.Types.CSharpType.get_Implementation() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Types\CSharpType.cs:line 62
     at AutoRest.CSharp.Output.Models.RestClientBuilder.CreateParameter(RequestParameter requestParameter) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 383
     at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildMethod(Operation operation, HttpRequest httpRequest, IEnumerable`1 requestParameters, DataPlaneResponseHeaderGroupType responseHeaderModel, String accessibility) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 76
  [4.97 s] Generation Complete
     at AutoRest.CSharp.Output.Models.LowLevelRestClient.BuildAllMethods()+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelRestClient.cs:line 61
     at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.LowLevelRestClient.get_Methods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelRestClient.cs:line 41
     at AutoRest.CSharp.Generation.Writers.LowLevelClientWriter.WriteClient(CodeWriter writer, LowLevelRestClient client, BuildContext context) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\LowLevelClientWriter.cs:line 32
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 23
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 46
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
```

[CodeModel.zip](https://github.com/Azure/autorest.csharp/files/6649294/CodeModel.zip)

**Comment by ellismg** [comment]
Talking with @AlexanderSher about this - I think this is no longer a key issue because we do not plan to do grouping/flattening - we should update our configuration that we flow to M4 when running in low-level-client model to disable grouping/flattening.  This is in line with what other languages (Python) is doing, based on my understanding.

**Comment by annelo-msft** [comment]
LLC is not compatible with grouping and flattening.

- [ ] Action here is to disable flattening ability - turn this off by default for LLC flow.

The problem is that if we use flattening you could have collisions of children at the root, e.g.

**Comment by lmazuel** [comment]
I suggest a section like that in your Readme:
![image](https://user-images.githubusercontent.com/1050156/133344506-d497a493-bba6-47a0-9c8d-36d0dd4a5ac4.png)

https://raw.githubusercontent.com/Azure/autorest.python/autorestv3/README.md

**Comment by ellismg** [comment]
Opened #1520 to address this - thanks for the helpful pointer @lmazuel!
