### ISSUE TITLE
[Azure.Anaytics.Synapse.Artifacts] Deserialization exception from CodeModel.yaml

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1454]
I am trying to generate code for the `Azure.Anaytics.Synapse.Artifacts` from an updated `autorest.md` file pointing to the service team's new preview swagger:
- `autorest.md`: https://github.com/Azure/azure-sdk-for-net/pull/23132/commits/511946efb4789de741e128f927b724651f40c10c#diff-c5d644299c0fe037d2d3ba972e0bf0b9631dbc07b1f8818fd88bdcc5fc8b3d0bR13

(i.e. [this API Spec](https://github.com/Azure/azure-rest-api-specs/blob/c981b81aa26ad4d0d156e034e6782853b4e747a1/specification/synapse/data-plane/readme.md) with the tag `package-artifacts-2021-06-01-preview`)

I am getting the following exception:

YamlDotNet.Core.YamlException: '(Line: 51548, Col: 11, Idx: 3358409) - (Line: 51548, Col: 11, Idx: 3358409): Exception during deserialization'

YamlDotNet.Core.YamlException
  HResult=0x80131500
  Message=(Line: 51548, Col: 11, Idx: 3358409) - (Line: 51548, Col: 11, Idx: 3358409): Exception during deserialization
  Source=YamlDotNet
  StackTrace:
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at AutoRest.CSharp.Input.CodeModelSerialization.DeserializeCodeModel(String yaml) in C:\src\autorest.csharp\src\AutoRest.CSharp\Common\Input\CodeModelSerialization.cs:line 52

  This exception was originally thrown at this call stack:
    System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
    YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(object, System.Type, System.Globalization.CultureInfo)
    YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(object, System.Type)
    YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(System.Type, YamlDotNet.Core.IParser, System.Func<YamlDotNet.Core.IParser, System.Type, object>, System.Collections.IList, bool)
    YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(YamlDotNet.Core.IParser, System.Type, System.Func<YamlDotNet.Core.IParser, System.Type, object>, out object)
    YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(YamlDotNet.Core.IParser, System.Type, YamlDotNet.Serialization.Utilities.SerializerState, YamlDotNet.Serialization.IValueDeserializer)

Inner Exception 1:
InvalidCastException: Object must implement IConvertible.

Files:
[CodeModelAndConfiguration.zip](https://github.com/Azure/autorest.csharp/files/6941072/CodeModelAndConfiguration.zip)

**Comment by AlexanderSher** [comment]
Issue moved to [Azure/autorest #4264](https://github.com/Azure/autorest/issues/4264) via [**ZenHub**](https://www.zenhub.com/)
