### ISSUE TITLE
[bug] Generation fails when a multipart requestBody includes a boolean property

### ISSUE THREAD

**Issue by cfculhane** [Azure/autorest.csharp#1455]
**Describe the issue or request**
I have a endpoint with a request multipart/form-data requestBody containing a number of properties, including a boolean field. When generating, it fails with the error:

```Exception: The method or operation is not implemented.
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildRequestBody(IList1 requestParameters, Dictionary2 allParameters, KnownMediaType mediaType) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 343
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildRequest(HttpRequest httpRequest, IList1 requestParameters, Dictionary2 allParameters) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 143
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildMethod(Operation operation, HttpRequest httpRequest, IEnumerable`1 requestParameters, DataPlaneResponseHeaderGroupType responseHeaderModel, String accessibility, Boolean returnNullOn404) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 79
   at AutoRest.CSharp.Output.Models.DataPlaneRestClient.EnsureNormalMethods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\Output\DataPlaneRestClient.cs:line 36
   at AutoRest.CSharp.Utilities.CachedDictionary`2.EnsureValues() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Utilities\CachedDictionary.cs:line 32
   at AutoRest.CSharp.Output.Models.RestClient.BuildAllMethods()+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClient.cs:line 59
   at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.RestClient.get_Methods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClient.cs:line 48
   at AutoRest.CSharp.Generation.Writers.RestClientWriter.WriteClient(CodeWriter writer, RestClient restClient) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\RestClientWriter.cs:line 33
   at AutoRest.CSharp.AutoRest.Plugins.DataPlaneTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\AutoRest\DataPlaneTarget.cs:line 52
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 56
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
```

If I remove the boolean property and leave the remaining (string) fields, it generates no problem. I have tried this with the most recent stable release, as well as the most recent build (`autorest --version:https://tinyurl.com/yh7y5n76 --use:https://tinyurl.com/ygcjp8d5 --csharp readme.md`)

Minimal reproducible example:

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    post:
      summary: Create a pet
      description: Create a pet
      operationId: createPets
      responses:
        '201':
          description: Null response
      requestBody:
        description: Pet request body that breaks C#
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              additionalProperties: false
              properties:
                file:
                  type: string
                  format: binary
                  description: File as binary data blob
                wait:
                  type: boolean
                  description: This is the description for this broken property
```

If you remove the `wait` property, it will generate just fine. 

Note that the above generates just fine in the other auto rest code generators, it only seems to be C# that doesn't work with this.

**Comment by cfculhane** [comment]
A guess - this doesn't seem to be neccesarily because of the *boolean* so much as having a multipart object of different types?

Another example, if you have an object with two `string` properties, and one of them is `format: url` , the same error occurs, e.g. 

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    post:
      summary: Create a pet
      description: Create a pet
      operationId: createPets
      responses:
        '201':
          description: Null response
      requestBody:
        description: Pet request body that breaks C#
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              additionalProperties: false
              properties:
                file_url:
                  type: string
                  format: url
                  description: URL to file to upload
                another_property:
                  type: string
                  description: Another random prop

```

**Comment by cfculhane** [comment]
Bump - any others come across this error? For now I've added some directives to remove any non-string fields in the requestBody but that is very limiting for our particular API use case.
