### ISSUE TITLE
Internal error in AutoRest.CSharp: "The method or operation is not implemented."

### ISSUE THREAD

**Issue by leus** [Azure/autorest.csharp#1566]
When compiling my model, got the following error. I'm not sure if this is related to #1551. 

Attached CodeModel.yaml and Configuration.json files: [Configuration.zip](https://github.com/Azure/autorest.csharp/files/7340416/Configuration.zip)
```
Exception: The method or operation is not implemented.
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildRequestBody(IList1 requestParameters, Dictionary2 allParameters, KnownMediaType mediaType) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 345
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildRequest(HttpRequest httpRequest, IList1 requestParameters, Dictionary2 allParameters) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 143
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildMethod(Operation operation, HttpRequest httpRequest, IEnumerable1 requestParameters, DataPlaneResponseHeaderGroupType responseHeaderModel, String accessibility, Func2 returnNullOn404Func) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 79
   at AutoRest.CSharp.Output.Models.DataPlaneRestClient.EnsureNormalMethods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\Output\DataPlaneRestClient.cs:line 36
   at AutoRest.CSharp.Utilities.CachedDictionary`2.EnsureValues() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Utilities\CachedDictionary.cs:line 32
   at AutoRest.CSharp.Output.Models.RestClient.BuildAllMethods()+MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClient.cs:line 58
   at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.RestClient.get_Methods() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClient.cs:line 47
   at AutoRest.CSharp.Generation.Writers.RestClientWriter.WriteClient(CodeWriter writer, RestClient restClient) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\RestClientWriter.cs:line 34
   at AutoRest.CSharp.AutoRest.Plugins.DataPlaneTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\AutoRest\DataPlaneTarget.cs:line 52
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 56
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
info    | Generation Complete
```

**Comment by AlexGhiondea** [comment]
@AlexanderSher @ShivangiReja does this sound familiar?

**Comment by leus** [comment]
@AlexanderSher different ones, already covered in the linked issue.
