### ISSUE TITLE
Internal error in AutoRest.CSharp Exception: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by hquangthinh** [Azure/autorest.csharp#1613]
fatal   | Internal error in AutoRest.CSharp
   Please file an issue at https://github.com/Azure/autorest.csharp/issues/new.
   Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

Exception: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source, Func2 predicate)
   at AutoRest.CSharp.Generation.Writers.Co
deWriterExtensions.<>c_DisplayClass21_0.<WriteInitialization>b_0(ObjectTypeProperty property) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\CodeWriterExtensions.cs:line 387

Attached with  'Configuration.json' and 'CodeModel.yaml' in a zip file  [codemodel_and_configuration.zip](https://github.com/Azure/autorest.csharp/files/7388260/codemodel_and_configuration.zip)

Platform Windows 10

autorest --info
AutoRest code generation utility [cli version: 3.4.2; node: v12.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions

 Type       Extension Name                           Version      
 core       @autorest/core                           3.6.6        
 extension  @autorest/csharp                         3.0.0-beta.20211018.1 
 extension  @autorest/csharp                         3.0.0-beta.20211019.2 
 extension  @autorest/modelerfour                    4.21.1

**Comment by AlexanderSher** [comment]
```cs
Unhandled exception. System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoRest.CSharp.Generation.Writers.CodeWriterExtensions.<>c__DisplayClass21_0.<WriteInitialization>b__0(ObjectTypeProperty property) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\CodeWriterExtensions.cs:line 387
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Generation.Writers.CodeWriterExtensions.WriteInitialization(CodeWriter writer, Action`2 valueCallback, ObjectType objectType, ObjectTypeConstructor constructor, IEnumerable`1 initializers) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\CodeWriterExtensions.cs:line 385
   at AutoRest.CSharp.Generation.Writers.ModelFactoryWriter.WriteFactoryMethodForSchemaObjectType(CodeWriter writer, MethodSignature method) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelFactoryWriter.cs:line 42
   at AutoRest.CSharp.Generation.Writers.ModelFactoryWriter.WriteModelFactory(CodeWriter writer, ModelFactoryTypeProvider modelFactoryType) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelFactoryWriter.cs:line 22
   at AutoRest.CSharp.AutoRest.Plugins.DataPlaneTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\DataPlane\AutoRest\DataPlaneTarget.cs:line 45
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 54
   at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(String[] args) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 25
   at AutoRest.CSharp.Program.Main(String[] args) in C:\GitHub\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 28
   at AutoRest.CSharp.Program.<Main>(String[] args)
```

**Comment by AlexanderSher** [comment]
`ErpAPInvDtlSearchListItem` schema has two properties with the same name - `POLineDesc`. Can you provide an input swagger?

**Comment by AlexanderSher** [comment]
Closing since https://github.com/Azure/autorest/issues/4363 is resolved.
