### ISSUE TITLE
HTTP 202 will throw error in ApplicationGateway.Start

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1653]
# Description
This needs further investigation. But in the current test case, `ApplicationGateway.Start` will throw an error like below. This could be due to back-end service not strictly follow the LRO spec. But it takes 45 minutes to create an application, so we need further investigation on this case.

```
Error Message:
   Azure.RequestFailedException : Service request failed.
Status: 202 (Accepted)

Content:
null

Headers:
Pragma: no-cache
x-ms-request-id: a38e1ce9-2bed-4d00-a23b-375e19229646
x-ms-client-request-id: 5696b0c46de2a5e742317089beba8b54
Azure-AsyncOperation: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-arm-service-request-id: REDACTED
Strict-Transport-Security: REDACTED
Content-Length: 4
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Location: REDACTED
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 27 Aug 2021 08:33:27 GMT

  Stack Trace:
     at Azure.Core.OperationInternals.<UpdateStatusAsync>d__23.MoveNext() in C:\Users\mingzhehuang\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210826.1\content\Generator.Shared\OperationInternals.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternals.<UpdateStatusAsync>d__25.MoveNext() in C:\Users\mingzhehuang\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210826.1\content\Generator.Shared\OperationInternals.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternals.<WaitForCompletionResponseAsync>d__22.MoveNext() in C:\Users\mingzhehuang\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20210826.1\content\Generator.Shared\OperationInternals.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.ResourceManager.Network.ApplicationGateway.<StartAsync>d__27.MoveNext() in C:\Users\mingzhehuang\workspaces\azure\azure-sdk-for-net\sdk\network\Azure.ResourceManager.Network\src\Generated\ApplicationGateway.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.ResourceManager.Network.Tests.Tests.ApplicationGatewayTests.<AppGatewayBackendHealthCheckTest>d__10.MoveNext() in C:\Users\mingzhehuang\workspaces\azure\azure-sdk-for-net\sdk\network\Azure.ResourceManager.Network\tests\Tests\ApplicationGatewayTests.cs:line 852
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

----
[Note]: This is migrated from [ADO 6162](https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_workitems/edit/6162/).

**Comment by archerzz** [comment]
After some investigation, it's due to `Network` API doesn't follow the spec. According to the spec:
> The API flow for POST {resourceUrl}/{action} should be:
>
> Respond to the initial POST request with a 202 Accepted
> The response headers MUST include a Location header that points to a URL where the ongoing operation can be monitored (as described below).
> Optional: The response headers may include an Azure-AsyncOperation header pointing to an Operation resource (as described below).
> If the POST completes successfully, the URL that was returned in the Location header MUST now return what would have been a successful response if the API completed (e.g. a response body / header / status code). It is acceptable for this to be a 200/204 NoContent if the action does not require a response (e.g. restarting a VM).

In the response of the `POST` request, both `Location` and `Azure-AsyncOperation` are returned. The second request is sent to URL specified in `Azure-AsyncOperation`, which returns `Succeeded`. Then the same request to URL in `Location` should return `Succeeded` as well. But in the logs, you can see it returns HTTP 202 with no content which by spec means the process is not finished. That is inconsistent, and both query URLs should return the same state.

---

## Background
In the common logic of LRO https://github.com/Azure/autorest.csharp/blob/af581b9f3703417f9d9597612fbd6db942d3193d/src/assets/Generator.Shared/OperationInternals.cs#L111
After a terminal state is detected (e.g. `succeeded, failed, canceled`), the current LRO logic will try to fetch the result from a `finalUri`. This is because some API need an extra request to return the data. 

For this case, the `finalUri` is `Location: https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/providers/Microsoft.Network/locations/westus2/operationResults/8cb093ca-9828-4952-8254-1ffbacc50e14?api-version=2021-02-01`.
And it doesn't return the same state of `Azure-AsyncOperation: https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/providers/Microsoft.Network/locations/westus2/operations/8cb093ca-9828-4952-8254-1ffbacc50e14?api-version=2021-02-01`.

**Comment by weidongxu-microsoft** [comment]
Live log from Java, seems final result follows Location header, and get code 200.

POST
```
[ForkJoinPool-1-worker-51] INFO com.azure.resourcemanager.network.implementation.ApplicationGatewaysClientImpl$ApplicationGatewaysService.start - --> POST https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg295620eb/providers/Microsoft.Network/applicationGateways/ag968357257/start?api-version=2021-03-01
Try count: 1
Date:Fri, 05 Nov 2021 16:07:22 GMT
Authorization:REDACTED
Content-Length:0
x-ms-return-client-request-id:true
Content-Type:application/json
x-ms-client-request-id:f6f4ca1e-945a-4b6d-a591-018f7637b1cc
Accept:application/json
User-Agent:azsdk-java-com.azure.resourcemanager.network/2.10.0-beta.1 (15.0.1; Windows 10; 10.0)
(empty body)
--> END POST

[reactor-http-nio-2] INFO com.azure.resourcemanager.network.implementation.ApplicationGatewaysClientImpl$ApplicationGatewaysService.start - <-- 202 https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg295620eb/providers/Microsoft.Network/applicationGateways/ag968357257/start?api-version=2021-03-01 (414 ms, 0-byte body)
Cache-Control:no-cache
Pragma:no-cache
Expires:-1
Location:https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operationResults/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
Retry-After:10
x-ms-request-id:e6a01b08-051c-4701-9178-cf96a00ede60
x-ms-client-request-id:f6f4ca1e-945a-4b6d-a591-018f7637b1cc
Azure-AsyncOperation:https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operations/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
x-ms-correlation-request-id:2cb4090c-72fd-4a9e-b327-28c1edd2a553
x-ms-arm-service-request-id:24fca84c-7b5f-43a6-8b3b-dbb20425a790
Strict-Transport-Security:max-age=31536000; includeSubDomains
Server:Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes:1199
x-ms-routing-request-id:JAPANEAST:20211105T160721Z:2cb4090c-72fd-4a9e-b327-28c1edd2a553
X-Content-Type-Options:nosniff
Date:Fri, 05 Nov 2021 16:07:20 GMT
content-length:0
(body content not logged)
<-- END HTTP
```

Last poll
```
[parallel-5] INFO  - --> GET https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operations/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
Try count: 1
Date:Fri, 05 Nov 2021 16:22:47 GMT
Authorization:REDACTED
x-ms-return-client-request-id:true
x-ms-client-request-id:e087db0e-f847-4c5a-9c96-132d0690225f
Accept:application/json
User-Agent:azsdk-java-com.azure.resourcemanager.resources.fluentcore.policy/null (15.0.1; Windows 10; 10.0)
(empty body)
--> END GET

[reactor-http-nio-3] INFO  - <-- 200 https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operations/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01 (314 ms, 50-byte body)
Cache-Control:no-cache
Pragma:no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
x-ms-request-id:cca3b9f5-c2f5-4a68-abaf-aa04270abdcf
x-ms-client-request-id:e087db0e-f847-4c5a-9c96-132d0690225f
x-ms-correlation-request-id:ac98e15e-244d-4078-9b03-5229ae0c6e59
x-ms-arm-service-request-id:a5ed42af-95dc-46d2-bac5-b326955bce14
Strict-Transport-Security:max-age=31536000; includeSubDomains
Server:Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads:11993
x-ms-routing-request-id:JAPANEAST:20211105T162246Z:ac98e15e-244d-4078-9b03-5229ae0c6e59
X-Content-Type-Options:nosniff
Date:Fri, 05 Nov 2021 16:22:45 GMT
content-length:50
Response body:
{
  "status" : "Succeeded",
  "properties" : { }
}
<-- END HTTP
```

Final result
```
[reactor-http-nio-3] INFO  - --> GET https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operationResults/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
Try count: 1
Date:Fri, 05 Nov 2021 16:22:47 GMT
Authorization:REDACTED
x-ms-return-client-request-id:true
x-ms-client-request-id:c5d39acd-7d67-4e95-aa49-ea77eb9721ff
Accept:application/json
User-Agent:azsdk-java-com.azure.resourcemanager.resources.fluentcore.policy/null (15.0.1; Windows 10; 10.0)
(empty body)
--> END GET

[reactor-http-nio-3] INFO  - <-- 200 https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operationResults/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01 (742 ms, 4-byte body)
Cache-Control:no-cache
Pragma:no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
Location:https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operationResults/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
x-ms-request-id:e6a01b08-051c-4701-9178-cf96a00ede60
x-ms-client-request-id:f6f4ca1e-945a-4b6d-a591-018f7637b1cc
Azure-AsyncOperation:https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Network/locations/eastus/operations/e6a01b08-051c-4701-9178-cf96a00ede60?api-version=2021-03-01
x-ms-correlation-request-id:2cb4090c-72fd-4a9e-b327-28c1edd2a553
x-ms-arm-service-request-id:24fca84c-7b5f-43a6-8b3b-dbb20425a790
Strict-Transport-Security:max-age=31536000; includeSubDomains
Server:Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads:11999
x-ms-routing-request-id:JAPANEAST:20211105T162246Z:89fc0f38-5eee-4369-ad8a-4ed10761ec7e
X-Content-Type-Options:nosniff
Date:Fri, 05 Nov 2021 16:22:46 GMT
content-length:4
Response body:
null
<-- END HTTP
```

Old recording (it is not 2021-02-01) https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/test/resources/session-records/ApplicationGatewayTests.testAppGatewaysStartStop.json#L1248

**Comment by archerzz** [comment]
This issue seems a defect in backend service. So I filed https://github.com/Azure/azure-rest-api-specs/issues/16734 on `Network`.

Meanwhile, during the diagnosis, some problems are revealed in the current LRO logic. I'll raise a PR to fix them.
