### ISSUE TITLE
Intermittent OOM in unit test

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1817]
## Problem

From time to time, we hit the following out of memory error in the unit test on pipeline. Although we could enlarge the memory limit for pipeline, we'd better diagnose the root cause, because previously there is no OOM error. It seems the memory footprint deteriorated during last few months.

```
 Failed ValidateRequiredParamsInCtor [688 ms]
  Error Message:
   System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
  Stack Trace:
     at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at System.Reflection.Internal.NativeHeapMemoryBlock.DisposableData..ctor(Int32 size)
   at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Boolean isFileStream, Int64 start, Int32 size)
   at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Int32 size)
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at AutoRest.CSharp.AutoRest.Plugins.GeneratedCodeWorkspace.CreateGeneratedCodeProject() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\GeneratedCodeWorkspace.cs:line 155
   at AutoRest.CSharp.AutoRest.Plugins.GeneratedCodeWorkspace.Create(String projectDirectory, String outputDirectory, String[] sharedSourceFolders) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\GeneratedCodeWorkspace.cs:line 111
   at AutoRest.TestServer.Tests.Mgmt.OutputLibrary.OutputLibraryTestBase.Generate(String testProject, String subFolder) in D:\a\1\s\autorest.csharp\test\AutoRest.TestServer.Tests\Mgmt\OutputLibrary\OutputLibraryTestBase.cs:line 48
   at AutoRest.TestServer.Tests.Mgmt.TestProjects.TestProjectTests.ValidateRequiredParamsInCtor() in D:\a\1\s\autorest.csharp\test\AutoRest.TestServer.Tests\Mgmt\TestProjects\TestProjectTests.cs:line 430
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

**Comment by AlexanderSher** [comment]
The issue is caused by the following static dictionaries that accumulate almost whole code model tree for each test:
- `AutoRest.CSharp.Mgmt.Decorator.InheritanceChooser._valueCache`
- `AutoRest.CSharp.Mgmt.Decorator.ParentDetection._requestPathToParentCache`
- `AutoRest.CSharp.Mgmt.Decorator.ParentDetection._operationToParentRequestPathCache`
- `AutoRest.CSharp.Mgmt.Decorator.ParentDetection._resourceParentCache`
- `AutoRest.CSharp.Mgmt.Decorator.ReferenceTypePropertyChooser._valueCache`
- `AutoRest.CSharp.Mgmt.Decorator.ResourceTypeBuilder._resourceDataSchemaNameCache`
- `AutoRest.CSharp.Mgmt.Decorator.ResourceTypeBuilder._requestPathToResourceTypeCache`
- `AutoRest.CSharp.Mgmt.Decorator.ScopeDetection._scopePathCache`
- `AutoRest.CSharp.Mgmt.Decorator.ScopeDetection._scopePathCache`
- `AutoRest.CSharp.Mgmt.Decorator.SingletonDetection._singletonResourceCache`
- `AutoRest.CSharp.Mgmt.Decorator.TypeReferenceTypeChooser._valueCache`
