### ISSUE TITLE
autorest.csharp errors out on "final-state-via: operation-location"

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest.csharp#2177]
**Describe the issue or request**

The [documentation for the "x-ma-long-running-operation-options" autorest extension](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-long-running-operation-options) says that there are four values allowed for the "final-state-via" field: one of `azure-async-operation` or `location` or `original-uri` or `operation-location`.

But when I try to specify:
```
"x-ms-long-running-operation-options": {"final-state-via": "operation-location"}
```
autorest.csharp failed with
```
  fatal   | Internal error in AutoRest.CSharp
     Please file an issue at https://github.com/Azure/autorest.csharp/issues/new. 
     Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.
  
  Exception: Unknown final-state-via value: operation-location
     at AutoRest.CSharp.Input.Operation.getLongRunningFinalStateVia() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\CodeModelPartials.cs:line 37
     at AutoRest.CSharp.Generation.Writers.LowLevelClientWriter.WriteLongRunningOperationMethod(CodeWriter writer, LowLevelClientMethod clientMethod, ClientFields fields, Boolean async) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\LowLevelClientWriter.cs:line 303
     at AutoRest.CSharp.Generation.Writers.LowLevelClientWriter.WriteClient(CodeWriter writer, LowLevelClient client, BuildContext`1 context) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\LowLevelClientWriter.cs:line 55
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 20
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 32
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 89
  fatal   | Process() cancelled due to failure 
```

**Describe your ideas for solutions**

autorest.csharp should recognize this value and handle it appropriately. 

**To Recreate**

- Clone https://github.com/mikekistler/azure-sdk-for-net.git
- Checkout branch `bug-2177`
- cd sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/src
- dotnet build /t:GenerateCode

**Comment by AlexanderSher** [comment]
`operation-location` is added in https://github.com/Azure/autorest/commit/90d697189c2528a524365e007a08d316e4aca5fb#diff-fa5fc18e9a8ded1bd61386a2277e9f4c47591ae7edccdce31affed8162094d86R1089

**Comment by archerzz** [comment]
This should have been fixed.
- See the `DevCenter` swagger spec which contains `"final-state-via": "operation-location"`: https://github.com/Azure/azure-rest-api-specs/blob/def187e2e78d7173d8fdd7f77740dd9719e1dfbf/specification/devcenter/data-plane/Microsoft.DevCenter/stable/2023-04-01/devbox.json#L535
- The codes are generated: https://github.com/Azure/azure-sdk-for-net/blob/031a2f81a1f067fa2588e177c7325e397144f608/sdk/devcenter/Azure.Developer.DevCenter/src/Generated/DevBoxesClient.cs#L912
- And there are test cases: https://github.com/Azure/azure-sdk-for-net/blob/031a2f81a1f067fa2588e177c7325e397144f608/sdk/devcenter/Azure.Developer.DevCenter/tests/DevBoxCreateTests.cs#L55-L58

However, there is no test case in `autorest.csharp`, nor in `autorest.testserver`. There is an issue on `autorest.testserver`: https://github.com/Azure/autorest.testserver/issues/243  We could contribute to `autorest.testserver`. So better to keep this issue open but with low priority.

**Comment by chunyu3** [comment]
This issue is resolved. close it.
