### ISSUE TITLE
Exception: Required conditional request headers are not supported.

### ISSUE THREAD

**Issue by Selekena** [Azure/autorest.csharp#2178]
I attempted to run on the [config](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceprovisioningservices/resource-manager/readme.md): 

> autorest --csharp

Exception: Required conditional request headers are not supported.
   at AutoRest.CSharp.Output.Models.RestClientBuilder.CreateRequestMethodBuildContext(HttpRequest httpRequest, IEnumerable`1 requestParameters) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 221
   at AutoRest.CSharp.Output.Models.RestClientBuilder.BuildRequestMethod(Operation operation, ServiceRequest serviceRequest, HttpRequest httpRequest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\RestClientBuilder.cs:line 86
   at AutoRest.CSharp.Output.Models.LowLevelClient.BuildMethods(RestClientBuilder builder, IEnumerable`1 serviceRequests, String clientName)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 89
   at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.LowLevelClient..ctor(String name, String ns, String description, Boolean isSubClient, IReadOnlyList1 subClients, IEnumerable1 serviceRequests, RestClientBuilder builder, BuildContext`1 context, ClientOptionsTypeProvider clientOptions) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 64
   at AutoRest.CSharp.Output.Models.LowLevelOutputLibraryFactory.CreateClients(IEnumerable1 topLevelClientInfos, BuildContext1 context, ClientOptionsTypeProvider clientOptions)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelOutputLibraryFactory.cs:line 210
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at AutoRest.CSharp.Output.Models.LowLevelOutputLibraryFactory.EnumerateAllClients(IEnumerable`1 topLevelClients) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelOutputLibraryFactory.cs:line 72
   at AutoRest.CSharp.Output.Models.LowLevelOutputLibraryFactory.<>c_DisplayClass0_0.<Create>b__2() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelOutputLibraryFactory.cs:line 33
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 15
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 49
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 89
fatal   | Process() cancelled due to failure
error   |   Error: Plugin csharpgen reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.

**Comment by Selekena** [comment]
I am wondering if its referring to the presence of these definitions in our swagger:
{
  "name": "If-Match",
  "in": "header",
  "required": true,
  "type": "string",
  "description": "ETag of the certificate."
},

If that is the case, how come it is failing now when this has been in our spec for years? Alternatively is referring to an issue in our autorest configuration file?

**Comment by Selekena** [comment]
Update: Once I removed all the of the required: "true" parameters (like seen above) for our etags, autorest was able to succeed. What changed with autorest that its now pushing for breaking changes in our swagger?

**Comment by AlexanderSher** [comment]
From the config, it looks like you need to generate ARM library, so please add `azure-arm: true` to the config.

**Comment by Selekena** [comment]
Worked like a charm!
