### ISSUE TITLE
`[JsonExtensionData]` only works with Dictionary<string, JToken>

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/autorest.csharp#258]
Newtonsoft.Json.JsonException occurred
  HResult=0x80131500
  Message=Invalid extension data attribute on 'MyType'. Member 'AdditionalProperties' type must implement IDictionary<string, JToken>.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c.<GetExtensionDataMemberForType>b__34_1(MemberInfo m)

The actual signature of that property is IDictionary<string,string> (which presumably autorest got out of the json schema of the swagger endpoint), but I don't see any evidence that JSON.Net supports anything other than JToken as the value type of the Dictionary.

I was using autorest 1.2.2 and NewtonSoft.Json 10.0.3

**Comment by rochapablo** [comment]
I'm not sure what I did, but it was working with this

```
[JsonExtensionData]
public List<string> Model { get; set; }
```

And now it stop working.

```
Invalid extension data attribute on 'Models.Query'. Member 'Model' type must implement IDictionary<string, JToken>.,    at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c.<GetExtensionDataMemberForType>b__44_1(MemberInfo m)   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType(Type type)   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContract(Type type)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(Type type)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()--- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by DzonnyDZ** [comment]
My bigger problem is that I'm getting the exception even though I provide a class implementing `IDictionary<string, JToken>` :-(.
I've created a class like `JDictionary<TValue>: Dictionary<string, TValue>, IDictionary<string, JToken>` and implemented it, but I'm still getting Type must implement IDictionary<string, JToken. :-(
