### ISSUE TITLE
C# CADL Generation issue

### ISSUE THREAD

**Issue by mpodwysocki** [Azure/autorest.csharp#2730]
**Describe the issue or request**

Trying to generate a C# project via CADL for [Azure Notification Hubs](https://github.com/mpodwysocki/azure-notificationhubs-cadl)

The CADL is being generated using the following where we have a relative path to the autorest Emitter.CSharp project

```bash
cadl compile main.cadl --emit ../autorest.csharp/src/CADL.Extension/Emitter.Csharp/dist/src/index.js --output-path cadl-output/csharp
```

After adding a [`Configuration.json`](https://github.com/mpodwysocki/azure-notificationhubs-cadl/blob/main/cadl-output/csharp/Configuration.json), I attempt to run the AutoRest.CSharp using the `cadl.json` as input such as the following:

```bash
~/git/autorest.csharp/artifacts/bin/AutoRest.CSharp/Debug/netcoreapp3.1/AutoRest.CSharp --standalone cadl-output/csharp/
```

This gives the following error:

```bash
Unhandled exception. AutoRest.CSharp.Utilities.ErrorHelpers+ErrorException: Exception of type 'AutoRest.CSharp.Utilities.ErrorHelpers+ErrorException' was thrown.
   at AutoRest.CSharp.Utilities.ErrorHelpers.ThrowError(String errorText) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/Common/Utilities/ErrorHelpers.cs:line 15
   at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.AddUriOrPathParameters(String uriPart, IReadOnlyDictionary`2 requestParameters) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/OperationMethodChainBuilder.cs:line 270
   at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.BuildParameters() in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/OperationMethodChainBuilder.cs:line 237
   at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder..ctor(InputOperation operation, String clientName, ClientFields fields, TypeFactory typeFactory) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/OperationMethodChainBuilder.cs:line 56
   at AutoRest.CSharp.Output.Models.LowLevelClient.<>c__DisplayClass50_0.<BuildMethods>b__1(InputOperation o) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs:line 84
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at AutoRest.CSharp.Output.Models.LowLevelClient.BuildMethods(TypeFactory typeFactory, IEnumerable`1 operations, ClientFields fields, String clientName)+MoveNext() in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs:line 84
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.LowLevelClient..ctor(String name, String ns, String description, String libraryName, LowLevelClient parentClient, IEnumerable`1 operations, IEnumerable`1 clientParameters, InputAuth authorization, SourceInputModel sourceInputModel, ClientOptionsTypeProvider clientOptions, TypeFactory typeFactory) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs:line 66
   at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.CreateClients(IEnumerable`1 clientInfos, TypeFactory typeFactory, ClientOptionsTypeProvider clientOptions, LowLevelClient parentClient)+MoveNext() in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/DpgOutputLibraryBuilder.cs:line 299
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.CreateClients(List`1 allClients, IEnumerable`1 topLevelClientInfos, TypeFactory typeFactory, ClientOptionsTypeProvider clientOptions) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/DpgOutputLibraryBuilder.cs:line 282
   at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.Build(Boolean isCadlInput) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/Output/DpgOutputLibraryBuilder.cs:line 63
   at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.Execute(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean cadlInput) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/LowLevel/AutoRest/LowLevelTarget.cs:line 15
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/Common/AutoRest/Plugins/CSharpGen.cs:line 62
   at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(String[] args) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/Common/AutoRest/Communication/StandaloneGeneratorRunner.cs:line 35
   at AutoRest.CSharp.Program.Main(String[] args) in <REDACTED>/git/autorest.csharp/src/AutoRest.CSharp/Program.cs:line 34
   at AutoRest.CSharp.Program.<Main>(String[] args)
[1]    47838 abort       --standalone cadl-output/csharp/
```

Environment:
- Branch: feature/v3
- OS: macOS 12.6
- Node.js version: 18.9.0
- .NET SDK version: 6.0.401

Briefly described issue with @AlexanderSher and indicated it may be an issue with the `{hubName}` parameter.  This is not an issue with the other libraries which Notification Hubs compiles for including Python, TypeScript and Java.

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by AlexanderSher** [comment]
[main.cadl](https://github.com/mpodwysocki/azure-notificationhubs-cadl/blob/main/main.cadl) declares two parameters in @server:
```
@server("https://{namespaceName}.servicebus.windows.net/{hubName}", "Notification Hubs Namespace", {
  @doc("Notification Hubs Namespace")
  namespaceName?: string,
  @doc("Notification Hub Name")
  hubName?: string,
})
```

[cadl.json](https://github.com/mpodwysocki/azure-notificationhubs-cadl/blob/main/cadl-output/csharp/cadl.json#L1613-L1631) contains only `namespaceName`

**Comment by chunyu3** [comment]
We will give out a fix to support multiple parameters in service url.
