### ISSUE TITLE
Cannot generate cadl of openai

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3011]
Generating using the cadl: https://github.com/Azure/azure-rest-api-specs/tree/ae31ea759e2a9ca194a48b474024f25c1d1e6436/specification/cognitiveservices/OpenAI.Inference
Exceptions are thrown:
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at AutoRest.CSharp.Utilities.StringExtensions.ToCleanName(String name, Boolean isCamelCase) in D:\a\_work\1\s\auto
  rest.csharp\src\AutoRest.CSharp\Common\Utilities\StringExtensions.cs:line 36
     at AutoRest.CSharp.Utilities.StringExtensions.ToVariableName(String name) in D:\a\_work\1\s\autorest.csharp\src\Au
  toRest.CSharp\Common\Utilities\StringExtensions.cs:line 95
     at AutoRest.CSharp.Output.Models.Shared.Parameter.FromInputParameter(InputParameter& operationParameter, CSharpTyp
  e type, TypeFactory typeFactory) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Shared\Pa
  rameter.cs:line 30
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.BuildParameter(InputParameter& operationParameter, CS
  harpType typeOverride) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\OperationMethodChainBuil
  der.cs:line 410
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.AddBody(InputParameter bodyParameter, InputParameter
  contentTypeRequestParameter) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\OperationMethodCha
  inBuilder.cs:line 321
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.BuildParameters() in D:\a\_work\1\s\autorest.csharp\s
  rc\AutoRest.CSharp\LowLevel\Output\OperationMethodChainBuilder.cs:line 270
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder..ctor(InputOperation operation, String clientName, Cl
  ientFields fields, TypeFactory typeFactory) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\Ope
  rationMethodChainBuilder.cs:line 57
     at AutoRest.CSharp.Output.Models.LowLevelClient.<>c__DisplayClass53_0.<BuildMethods>b__1(InputOperation o) in D:\a
  \_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 84
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSel
  ector, IEqualityComparer`1 comparer)
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 ele
  mentSelector, IEqualityComparer`1 comparer)
     at AutoRest.CSharp.Output.Models.LowLevelClient.BuildMethods(TypeFactory typeFactory, IEnumerable`1 operations, Cl
  ientFields fields, String clientName)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Outpu
  t\LowLevelClient.cs:line 84
     at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.LowLevelClient..ctor(String name, String ns, String description, String libraryNa
  me, LowLevelClient parentClient, IEnumerable`1 operations, IEnumerable`1 clientParameters, InputAuth authorization, S
  ourceInputModel sourceInputModel, ClientOptionsTypeProvider clientOptions, TypeFactory typeFactory) in D:\a\_work\1\s
  \autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 64
     at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.CreateClients(IEnumerable`1 clientInfos, TypeFactory type
  Factory, ClientOptionsTypeProvider clientOptions, LowLevelClient parentClient)+MoveNext() in D:\a\_work\1\s\autorest.
  csharp\src\AutoRest.CSharp\LowLevel\Output\DpgOutputLibraryBuilder.cs:line 0
     at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
     at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.CreateClients(List`1 allClients, IEnumerable`1 topLevelCl
  ientInfos, TypeFactory typeFactory, ClientOptionsTypeProvider clientOptions) in D:\a\_work\1\s\autorest.csharp\src\Au
  toRest.CSharp\LowLevel\Output\DpgOutputLibraryBuilder.cs:line 368
     at AutoRest.CSharp.Output.Models.DpgOutputLibraryBuilder.Build(Boolean isCadlInput) in D:\a\_work\1\s\autorest.csh
  arp\src\AutoRest.CSharp\LowLevel\Output\DpgOutputLibraryBuilder.cs:line 63
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inp
  utNamespace, SourceInputModel sourceInputModel, Boolean cadlInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSh
  arp\LowLevel\AutoRest\LowLevelTarget.cs:line 18
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autores
  t.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 60
     at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_
  work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 50
     at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\P
  rogram.cs:line 47
     at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Pr
  ogram.cs:line 29
```

**Comment by chunyu3** [comment]
The `ToCleanName` does not check if the input string is empty string, and directly access the first character which cause the crash.
We need to check if the string is empty, if so, throw exception for it.

And we may add check in cadl emitter to make sure the model name is not empty string, otherwise throw exception in the emitter.

**Comment by chunyu3** [comment]
Currently, most failure case is because of anonymous model.

**Comment by pshao25** [comment]
Please also consider this valid case:
```
@route("/test")
@doc("Doc.")
@post
op test(body: Model): Response<200>;
```
It should be generated correctly instead of throwing error.

**Comment by ArcturusZhang** [comment]
False alarm, resolved
