### ISSUE TITLE
Generate issue: Not a constant

### ISSUE THREAD

**Issue by dvbb** [Azure/autorest.csharp#3303]
related RP: CostManagement

### throw info
fatal   | Internal error in AutoRest.CSharp
     Please file an issue at https://github.com/Azure/autorest.csharp/issues/new.
     Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

  Exception: Not a constant
     at AutoRest.CSharp.Output.Models.Requests.ReferenceOrConstant.getConstant() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Requests\ReferenceOrConstant.cs:line 33     
     at AutoRest.CSharp.Mgmt.Models.Segment.getConstantValue() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Models\Segment.cs:line 86
     at AutoRest.CSharp.Mgmt.Output.MgmtExtension.<>c.<CalculateOperationName>b_43_0(Segment segment) in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtension.cs:line 121       
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.String.Join(String separator, IEnumerable`1 values)
     at AutoRest.CSharp.Mgmt.Output.MgmtExtension.CalculateOperationName(Operation operation, String clientResourceName) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtensi 
  on.cs:line 121
     at AutoRest.CSharp.Mgmt.Output.MgmtTypeProvider.GetOperationName(Operation operation, String clientResourceName) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtTypeProvid 
  er.cs:line 220
     at AutoRest.CSharp.Mgmt.Output.MgmtExtension.<>c_DisplayClass41_0.<EnsureClientOperations>b__0(Operation operation) in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtensio 
  n.cs:line 90
     at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
     at AutoRest.CSharp.Mgmt.Output.MgmtExtensionBuilder.EnsureMgmtExtensionInfo() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtensionBuilder.cs:line 68
     at AutoRest.CSharp.Mgmt.Output.MgmtExtensionBuilder.getExtensionInfo() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtensionBuilder.cs:line 45
     at AutoRest.CSharp.Mgmt.Output.MgmtExtensionBuilder.GetExtension(Type armCoreType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\MgmtExtensionBuilder.cs:line 41
     at AutoRest.CSharp.Mgmt.AutoRest.MgmtOutputLibrary.GetExtension(Type armCoreType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtOutputLibrary.cs:line 420
     at AutoRest.CSharp.Mgmt.Decorator.ParentDetection.DoGetParents(Resource resource) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\ParentDetection.cs:line 82
     at AutoRest.CSharp.Mgmt.Decorator.ParentDetection.GetParents(Resource resource) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\ParentDetection.cs:line 37
     at AutoRest.CSharp.Mgmt.Output.ResourceCollection.CreateDescription() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\ResourceCollection.cs:line 217
     at AutoRest.CSharp.Mgmt.Output.Resource.getDescription() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Output\Resource.cs:line 168
     at AutoRest.CSharp.Mgmt.Generation.MgmtClientBaseWriter.WriteClassDeclaration() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Generation\MgmtClientBaseWriter.cs:line 106
     at AutoRest.CSharp.Mgmt.Generation.MgmtClientBaseWriter.Write() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Generation\MgmtClientBaseWriter.cs:line 63
     at AutoRest.CSharp.AutoRest.Plugins.MgmtTarget.ExecuteAsync(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRes 
  t.CSharp\Mgmt\AutoRest\MgmtTarget.cs:line 86
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 43
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
  fatal   | Process() cancelled due to failure

**Comment by dvbb** [comment]
linked PR: https://github.com/Azure/azure-sdk-for-net/pull/35629
