### ISSUE TITLE
typespec-csharp error when discriminator defined in base type

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3421]
This is a bug with  "@azure-tools/typespec-csharp": "0.2.0-beta.20230518.1". It errors out when a discriminator is main public in the base type. The expectation is that it makes the field public instead of internal and does not error out. See the discussion leading up to [this example](https://github.com/microsoft/typespec/issues/1900#issuecomment-1534962485). I can produce the error with this main.tsp:

```
import "@typespec/http";
import "@typespec/versioning";

using TypeSpec.Http;
using TypeSpec.Versioning;

@service({
  title: "Pet API",
})
@versioned(ServiceApiVersions)
namespace Pet;

enum ServiceApiVersions {
  v2023_05: "2023-05",
}

@discriminator("kind")
model Pet {
  kind: string;
}

model Cat extends Pet {
  kind: "cat";
  meow: boolean;
}

model Dog extends Pet {
  kind: "dog";
  bark: boolean;
}

@route("/pet")
@get
op pet(): Pet;
```

The error is:
````
PS C:\Users\cataggar\ms\avs\src\conveyor\ConsumptionWorker\client> tsp compile .
TypeSpec compiler v0.44.0

{"level":"info","message":"routes:1"}
{"level":"info","message":"load operation: pet, path:/pet "}
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: kind
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.GetPropertyInitializers(IReadOnlyList`1 parameters, Boolean includeDiscriminator) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 283
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.BuildSerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 271
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_SerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 41
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.GetConstructorParameters(IEnumerable`1 parameters, List`1& fullParameterList, IEnumerable`1& parametersToPassToBase, Boolean isInitializer, Func`2 creator) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 244
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.CreateSerializationConstructorSignature(String name, IReadOnlyList`1 publicParameters, IReadOnlyList`1 serializationParameters) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 198
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.EnsureSerializationConstructorSignature() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 121
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.get_SerializationConstructorSignature() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 51
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.BuildConstructors()+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 356
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_Constructors() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 37
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteConstructor(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 348
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteObjectSchema(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 74
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteModel(CodeWriter writer, TypeProvider model) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 26
   at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean cadlInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 26
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 59
   at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 48
   at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47   
   at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29    
--- End of stack trace from previous location ---
   at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
   at AutoRest.CSharp.Program.<Main>(String[] args)
{"level":"info","message":"Command failed: dotnet --roll-forward Major C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client   --clear-output-folder true"}
ExternalError: Emitter "@azure-tools/typespec-csharp" failed!
File issue at https://github.com/Azure/autorest.csharp/issues

Error: Command failed: dotnet --roll-forward Major C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client   --clear-output-folder true    
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.$onEmit [as emitFunction] (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@azure-tools/typespec-csharp/dist/src/emitter.js:99:21)
    at async runEmitter (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:532:13)
    at async compile (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:242:9)
    at async Object.handler (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/cli/cli.js:118:25)
    at runEmitter (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:552:19)
    at async compile (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:242:9)
    at async Object.handler (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/cli/cli.js:118:25)
```

**Comment by chunyu3** [comment]
Hello @cataggar Above `single discrimiator and multiple level inheritance` scenario is not supported, it depends on how typespec to define this. We have an issue https://github.com/Azure/autorest.csharp/issues/3099 to track this.

**Comment by cataggar** [comment]
A `Pet` is a `Cat` or a `Dog` in that example. Isn't that single level inheritance?

**Comment by chunyu3** [comment]
> Dog

It is

**Comment by chunyu3** [comment]
hello @cataggar, in typespec, when you use @discriminator("kind"), it will add a property named "kind" into the model, it is not needed/allowed to add the property again.

you can define as following:

```
@discriminator("kind")
model Pet {
}

```

Thanks,

**Comment by chunyu3** [comment]
hello @cataggar  I saw you have updated the typespec accordingly. so this issue does not occur, can it be closed?

**Comment by cataggar** [comment]
> hello @cataggar, in typespec, when you use @Discriminator("kind"), it will add a property named "kind" into the model, it is not needed/allowed to add the property again.

Hi @chunyu3, please keep it open. It is valid TypeSpec to add the property to the model. It is allowed. Please see the example that I linked in the issue description.

**Comment by chunyu3** [comment]
already resolved this. Close it.
