### ISSUE TITLE
CSharp typespec emitter crashes

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest.csharp#3504]
The CSharp TypeSpec emitter crashes for the attached tsp file.
```
>tsp compile .
TypeSpec compiler v0.45.1

{"level":"info","message":"routes:1"}
{"level":"info","message":"load operation: read, path:/{id} "}
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: kind
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.GetPropertyInitializers(IReadOnlyList`1 parameters, Boolean includeDiscriminator) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 238
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.BuildSerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 226
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_SerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 41
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.GetConstructorParameters(IEnumerable`1 parameters, List`1& fullParameterList, IEnumerable`1& parametersToPassToBase, Boolean isInitializer, Func`2 creator) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 191
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.EnsureSerializationConstructorSignature() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 140
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.get_SerializationConstructorSignature() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 51
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.BuildSerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 221
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_SerializationConstructor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 41
   at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.BuildConstructors()+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 311
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_Constructors() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 37
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteConstructor(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 348
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteObjectSchema(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 74
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteModel(CodeWriter writer, TypeProvider model) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 26
   at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 26
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 59
   at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 50
   at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
   at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
--- End of stack trace from previous location ---
   at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
   at AutoRest.CSharp.Program.<Main>(String[] args)
{"level":"info","message":"Command failed: dotnet --roll-forward Major /Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path /Users/mikekistler/Projects/mikekistler/polymorphism/tsp-output/@azure-tools/typespec-csharp   --clear-output-folder false"}
ExternalError: Emitter "@azure-tools/typespec-csharp" failed!
File issue at https://github.com/Azure/autorest.csharp/issues

Error: Command failed: dotnet --roll-forward Major /Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path /Users/mikekistler/Projects/mikekistler/polymorphism/tsp-output/@azure-tools/typespec-csharp   --clear-output-folder false
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.$onEmit [as emitFunction] (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@azure-tools/typespec-csharp/dist/src/emitter.js:99:21)
    at async runEmitter (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/program.js:518:13)
    at async compile (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/program.js:243:9)
    at async Object.handler (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/cli/cli.js:125:25)
    at runEmitter (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/program.js:538:19)
    at async compile (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/program.js:243:9)
    at async Object.handler (file:///Users/mikekistler/Projects/mikekistler/polymorphism/node_modules/@typespec/compiler/dist/core/cli/cli.js:125:25)
```

[main.tsp.txt](https://github.com/Azure/autorest.csharp/files/11759552/main.tsp.txt)

**Comment by chunyu3** [comment]
Hello @mikekistler 
In typespec, when we define a polymorphism, we will use `@discriminator` to define/add a property of the base model which is discriminator (such as `kind`), so we should not define this property again in base model which cause duplicate property issue.

expected polymorphism definition:
```
import "@typespec/http";

using TypeSpec.Http;

@service({
  title: "Polymorphism",
  version: "2023-06-14"
})
namespace PolymorphicService;

@discriminator("kind")
model AudioBase {
}

model AudioMetadata extends AudioBase {
  kind: "AudioMetadata";
  subscriptionId: string;
  sampleRate: int32;
  format: string;
}

model AudioData extends AudioBase {
  kind: "AudioData";
  timestamp: utcDateTime;
  participantRawId: string;
  data: bytes;
  format: int32;
}

@error
model Error {
  code: int32;
  message: string;
}

@get op read(@path id: string): AudioBase | Error;


```

@mikekistler @m-nash Have we changed the polymorphism definition, and now `@discriminator` only indicate which property is discrminator, does not define a property and added to the model?

**Comment by cataggar** [comment]
I would be nice to look at what another emitter does when that property is defined in a `AusioBase` and when it is not.

**Comment by chunyu3** [comment]
> TypeSpec allows the discriminator property to be defined in `AudioBase`.

@mikekistler @cataggar the discriminator property will be defined with `@discriminator` decorator, it will not allow to define the property again in the base model `AudioBase`.  @m-nash has confirmed this with you about this.

**Comment by mikekistler** [comment]
TypeSpec _does allow_ the `kind` property to be defined in the base model.

See this [TypeSpec Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiUG9seW1vcnBoaXNtIiwKICB2ZXJzaW9uOiAiMjAyMy0wNi0xNCIKfSkKbmFtZXNwYWNlIMo0Y1PGU8ReZGlzY3JpbWluYXRvcigia2luZCIpCm1vZGVsIEF1ZGlvQmFzZSDEfMQbOiBzdHJpbmc7Cn0KzCVNZXRhZGF0YSBleHRlbmRz1TsizSsiOwogIHN1YsR%2FcHRpb25Jy14gIHNhbXBsZVJhdGU6IGludDMyxBVmb3JtYXT4AIVE%2FwCB5wCBxCfFfXRpbWVzdGFtcDogdXRjRGF0ZVRpbWXEGnBhcnRpY2lwYW50UmF37gCZ5AC8OiBieXRlc%2BwAk%2BcApH0KCkBlcnJvcucAmUXEDOUAg2NvZOwAy21lc3NhZ2XKWsQ6Z2V0IG9wIHJlYWQoQHBhdGggacl8KTrrANR8xlk7)

**Comment by archerzz** [comment]
IMHO, either we clean the excessive `@discriminator` properties in emitter, or we clean them in the generator. Considering in swagger definition there is no such issue (or at least we're not aware of), probably we clean them in the emitter.
