### ISSUE TITLE
Typespec generation fails for generic type

### ISSUE THREAD

**Issue by giulianob** [Azure/autorest.csharp#3655]
The following model fails generation
```
@doc("Facet")
model Facet {
   @doc("A field to facet by, where the field is attributed as 'facetable'")
   field: string;  
}

model NumericValuesFacet<T extends numeric> extends Facet {
  @doc("The facet ranges to produce. The values must be listed in ascending order to get the expected results. For example, values=10,20 produces three buckets: one for base rate 0 up to but not including 10, one for 10 up to but not including 20, and one for 20 and higher.")
  values: T[];
}

@doc("Facets an int32 field by the specified value ranges.")
model Int32ValuesFacet extends NumericValuesFacet<int32> {
  @doc("The facet type.")
  kind: "Int32Values";
}
```

This is the error I receive:
> EXEC : error : Unsupported type TemplateParameter
      at getInputType (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts:330:15)
      at node_modules/@azure-tools/typespec-csharp/src/lib/model.ts:619:35
      at node_modules/@typespec/compiler/src/core/util.ts:533:7
      at Map.forEach (<anonymous>)
      at RekeyableMapImpl.forEach (node_modules/@typespec/compiler/src/core/util.ts:532:18
  )
      at addModelProperties (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts:59
  6:25)
      at getInputModelForModel (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts
  :553:13)
      at getInputModelType (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts:342
  :16)
      at getInputType (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts:282:16)
      at getInputModelForModel (node_modules/@azure-tools/typespec-csharp/src/lib/model.ts
  :559:21)
      at runEmitter (node_modules/@typespec/compiler/src/core/program.ts:847:13)
      at compile (node_modules/@typespec/compiler/src/core/program.ts:413:5)
      at Object.handler (node_modules/@typespec/compiler/src/core/cli/cli.ts:143:25)

Using the following versions:
```
  "dependencies": {
    "@azure-tools/typespec-apiview": "^0.4.4",
    "@azure-tools/typespec-autorest": "^0.32.0",
    "@azure-tools/typespec-csharp": "^0.2.0-beta.20230803.1",
    "@typespec/compiler": "^0.46.0",
    "@typespec/json-schema": "^0.46.0",
    "@typespec/openapi3": "^0.46.0",
    "@typespec/rest": "^0.46.0"
  }
```

**Comment by chunyu3** [comment]
hello @giulianob We have not supported generic type yet. There is a issue https://github.com/Azure/autorest.csharp/issues/3263 to track this.

@giulianob would you please tell me the context where you need to define a generic type?  we will discuss and schedule to support generic type.
