### ISSUE TITLE
Random concurrent issue when accessing configuration.IntrinsicTypesToTreatEmptyStringAsNull

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3697]
Almost all of us have met this random issue: when generating code, there will be such duplicate item in a HashSet, which shouldn't.
![image](https://github.com/Azure/autorest.csharp/assets/97225342/c4391d9d-698e-4aaf-8d31-2b77a84fb8b5)

Very likely that two threads are updating the same `configuration.IntrinsicTypesToTreatEmptyStringAsNull` which is a global static instance (which means not thread safe).

Personally I met another issue once on my local machine, when accessing `configuration.IntrinsicTypesToTreatEmptyStringAsNull` at https://github.com/Azure/autorest.csharp/blob/f04ade5c151eda6c61ea401ae6516926391332a7/src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs#L451, with error
![image](https://github.com/Azure/autorest.csharp/assets/97225342/77ee2f98-04f9-4211-979e-94d042fed167)

Error message shows two threads are modifying the configuration.

**Some observation but might not be the root cause:**
Which makes `IntrinsicTypesToTreatEmptyStringAsNull` special is https://github.com/Azure/autorest.csharp/blob/f04ade5c151eda6c61ea401ae6516926391332a7/src/AutoRest.CSharp/Common/AutoRest/Plugins/Configuration.cs#L161

**Comment by pshao25** [comment]
To reproduce, I added these lines to `Configuration.Initialize`, which should only be called once.
![image](https://github.com/Azure/autorest.csharp/assets/97225342/10d5cbae-9bdc-4546-967a-5bdefe9a5328)
However, when I run ` .\eng\Generate.ps1 MgmtExactMatchInheritance`, the log shows it is called twice:
```
*****************************
.NET ThreadPool Worker
*****************************
8
.NET ThreadPool Worker
12
   at System.Environment.get_StackTrace()
   at AutoRest.CSharp.Input.Configuration.Initialize(String outputFolder, String ns, String libraryName, String[] sharedSourceFolders, Boolean saveInputs, Boolean azureArm, Boolean publicClients, Boolean modelNamespace, Boolean headAsBoolean, Boolean skipCSProjPackageReference, Boolean generation1ConvenienceClient, Boolean singleTopLevelClient, Boolean skipSerializationFormatXml, Boolean disablePaginationTopRenaming, Boolean generateModelFactory, Boolean publicDiscriminatorProperty, Boolean deserializeNullCollectionAsNullValue, Boolean useCoreDataFactoryReplacements, IReadOnlyList`1 modelFactoryForHlc, UnreferencedTypesHandlingOption unreferencedTypesHandling, Boolean useOverloadsBetweenProtocolAndConvenience, Boolean keepNonOverloadableProtocolSignature, String projectFolder, String existingProjectFolder, IReadOnlyList`1 protocolMethodList, IReadOnlyList`1 suppressAbstractBaseClasses, IReadOnlyList`1 modelsToTreatEmptyStringAsNull, IReadOnlyList`1 additionalIntrinsicTypesToTreatEmptyStringAsNull, Boolean shouldTreatBase64AsBinaryData, IReadOnlyList`1 methodsToKeepClientDefaultValue, MgmtConfiguration mgmtConfiguration, MgmtTestConfiguration mgmtTestConfiguration) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\Configuration.cs:line 101
   at AutoRest.CSharp.Input.Configuration.Initialize(IPluginCommunication autoRest, String defaultNamespace, String defaultLibraryName) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\Configuration.cs:line 289
   at AutoRest.CSharp.AutoRest.Plugins.CSharpProj.Execute(IPluginCommunication autoRest) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpProj.cs:line 99
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at AutoRest.CSharp.AutoRest.Communication.MessageHandling.JsonRpcConnection.Request[T](String id, String json) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\MessageHandling\JsonRpcConnection.cs:line 87
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(TResult result)
   at AutoRest.CSharp.AutoRest.Communication.MessageHandling.JsonRpcConnection.<>c__DisplayClass16_0.<HandleIncomingResponse>b__0() in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\MessageHandling\JsonRpcConnection.cs:line 74
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
*****************************
   at System.Environment.get_StackTrace()
   at AutoRest.CSharp.Input.Configuration.Initialize(String outputFolder, String ns, String libraryName, String[] sharedSourceFolders, Boolean saveInputs, Boolean azureArm, Boolean publicClients, Boolean modelNamespace, Boolean headAsBoolean, Boolean skipCSProjPackageReference, Boolean generation1ConvenienceClient, Boolean singleTopLevelClient, Boolean skipSerializationFormatXml, Boolean disablePaginationTopRenaming, Boolean generateModelFactory, Boolean publicDiscriminatorProperty, Boolean deserializeNullCollectionAsNullValue, Boolean useCoreDataFactoryReplacements, IReadOnlyList`1 modelFactoryForHlc, UnreferencedTypesHandlingOption unreferencedTypesHandling, Boolean useOverloadsBetweenProtocolAndConvenience, Boolean keepNonOverloadableProtocolSignature, String projectFolder, String existingProjectFolder, IReadOnlyList`1 protocolMethodList, IReadOnlyList`1 suppressAbstractBaseClasses, IReadOnlyList`1 modelsToTreatEmptyStringAsNull, IReadOnlyList`1 additionalIntrinsicTypesToTreatEmptyStringAsNull, Boolean shouldTreatBase64AsBinaryData, IReadOnlyList`1 methodsToKeepClientDefaultValue, MgmtConfiguration mgmtConfiguration, MgmtTestConfiguration mgmtTestConfiguration) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\Configuration.cs:line 101
   at AutoRest.CSharp.Input.Configuration.Initialize(IPluginCommunication autoRest, String defaultNamespace, String defaultLibraryName) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\Configuration.cs:line 289
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 81
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at AutoRest.CSharp.AutoRest.Communication.MessageHandling.JsonRpcConnection.Request[T](String id, String json) in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\MessageHandling\JsonRpcConnection.cs:line 87
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(TResult result)
   at AutoRest.CSharp.AutoRest.Communication.MessageHandling.JsonRpcConnection.<>c__DisplayClass16_0.<HandleIncomingResponse>b__0() in D:\GIT\pshao25.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\MessageHandling\JsonRpcConnection.cs:line 74
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
*****************************
```

**Comment by archerzz** [comment]
It seems that for swagger input, we'll run both `CSharpGen` and `CSharpProj`. It's hard coded in https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/readme.md
