### ISSUE TITLE
[DPG] Some Characters as enums cause IndexOutOfRangeException

### ISSUE THREAD

**Issue by quentinRobinson** [Azure/autorest.csharp#3763]
Enums that are special characters cause an IndexOutOfRangeException

We allow users to pick from a limited set of ascii characters to use as redaction characters and we represent those as enums.  

``` tsp
@doc("Optional parameter to use a Custom Character to be used for redaction in PII responses. Default character will be * as before. We allow specific ascii characters for redaction.")
enum RedactionCharacter{
    `!`,
    `#`,
    `$`,
    `%`,
    `&`,
    `*`,
    `+`,
    `-`,
    `=`,
    `?`,
    `@`,
    `^`,
    `_`,
    `~`,
}
```

The exception we get is shown below.
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at AutoRest.CSharp.Utilities.StringExtensions.ToCleanName(String name, Boolean isCamelCase) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Utilities\StringExtensions.cs:line 36
     at AutoRest.CSharp.Output.Models.Types.EnumType.BuildValues() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\EnumType.cs:line 82
     at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteExtensibleEnum(CodeWriter writer, EnumType enumType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 442
     at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteModel(CodeWriter writer, TypeProvider model) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 29
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 27
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 62
     at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 51
     at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
     at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
  --- End of stack trace from previous location ---
     at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
     at AutoRest.CSharp.Program.<Main>(String[] args)
```
**Describe your ideas for solutions**
Allow users to be able to use special characters as enums.

**Comment by quentinRobinson** [comment]
found sutible fix we can work around by giving enums names

``` tsp
@doc("Optional parameter to use a Custom Character to be used for redaction in PII responses. Default character will be * as before. We allow specific ascii characters for redaction.")
enum RedactionCharacter{
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    explationPoint: "!",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    numberSign: "#",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    dollar: "$",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    perCent: "%",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    ampersand: "&",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    asterisk: "*",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    plus: "+",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    minus: "-",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    equals: "=",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    questionMark: "?",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    atSign: "@",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    caret: "^",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    underscore: "_",
    #suppress "@azure-tools/typespec-azure-core/documentation-required"
    tilde: "~",
}
```
