### ISSUE TITLE
azure-tools/typespec-csharp: System.NotSupportedException: Required conditional request headers are not supported.

### ISSUE THREAD

**Issue by devlie** [Azure/autorest.csharp#3896]
We are migrating our swagger to TypeSpec and testing the SDK generation. The csharp emitter is stumbling on our API's conditional request header `If-None-Match`. That header param exists in our old Swagger too and we could generate SDK fine, so seems TypeSpec specific issue.

The error:
``` 
  {"level":"info","message":"dotnet --roll-forward Major D:/repos/azure-sdk-for-net/sdk/deviceupdate/Azure.IoT.DeviceUpdate/TempTypeSpecFiles/Microsoft.DeviceUpdate/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path
   D:/repos/azure-sdk-for-net/sdk/deviceupdate/Azure.IoT.DeviceUpdate/src --new-project  --clear-output-folder true"}
  Unhandled exception. System.NotSupportedException: Required conditional request headers are not supported.
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder.BuildParameters() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\OperationMethodChainBuilder.cs:line 456
     at AutoRest.CSharp.Output.Models.OperationMethodChainBuilder..ctor(LowLevelClient client, InputOperation operation, String namespaceName, String clientName, ClientFields fields, TypeFactory typeFactory, SourceInputModel sour
  ceInputModel, IReadOnlyDictionary`2 clientParameterExamples) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\OperationMethodChainBuilder.cs:line 68
     at AutoRest.CSharp.Output.Models.LowLevelClient.<>c__DisplayClass66_0.<BuildMethods>b__1(InputOperation o) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 126
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
     at AutoRest.CSharp.Output.Models.LowLevelClient.BuildMethods(LowLevelClient client, TypeFactory typeFactory, IEnumerable`1 operations, ClientFields fields, String namespaceName, String clientName, SourceInputModel sourceInpu
  tModel)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 126
     at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.LowLevelClient.get_AllClientMethods() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 98
     at AutoRest.CSharp.Output.Models.LowLevelClient.get_ClientMethods() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\LowLevelClient.cs:line 101
     at AutoRest.CSharp.Generation.Writers.DpgClientWriter.WriteClient() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\DpgClientWriter.cs:line 60
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\Auto
  Rest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 39
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 83
     at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 5
  1
     at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
     at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
  --- End of stack trace from previous location ---
     at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
     at AutoRest.CSharp.Program.<Main>(String[] args)
  {"level":"info","message":"Command failed: dotnet --roll-forward Major D:/repos/azure-sdk-for-net/sdk/deviceupdate/Azure.IoT.DeviceUpdate/TempTypeSpecFiles/Microsoft.DeviceUpdate/node_modules/@autorest/csharp/AutoRest.CSharp.dl
  l --project-path D:/repos/azure-sdk-for-net/sdk/deviceupdate/Azure.IoT.DeviceUpdate/src --new-project  --clear-output-folder true"}
  Emitter "@azure-tools/typespec-csharp" crashed! This is a bug.
  Please file an issue at https://github.com/Azure/autorest.csharp/issues
```

The typespec generated openapi:

```yaml
parameters:
    - name: if-none-match
      in: header
      required: false
      description: |-
        Defines the If-None-Match condition. The operation will be performed only if
        the ETag on the server does not match this value.
      schema:
        type: string
```

**Comment by chunyu3** [comment]
Thanks @devlie We will confirm with our arch if required conditional request header should support or not. Current we don't. And for deviceupdate, `If-not-match` is used to be optional parameter. Is there any reason that it is changed to required?

**Comment by devlie** [comment]
@chunyu3, it's still optional; the value is false

```yaml
      required: false
```

**Comment by chunyu3** [comment]
> @chunyu3, it's still optional; the value is false
> 
> ```yaml
>       required: false
> ```

Hello @devlie Would you please provide the typespec you use? It is strange, according to the error, it is required.

**Comment by devlie** [comment]
Sorry, I lost the repro. I must have done something stupid.
