### ISSUE TITLE
Proposal: Ignore failure responses when validating pageable method

### ISSUE THREAD

**Issue by a-ch-chu** [Azure/autorest.csharp#3987]
**Describe the issue or request**

The [ClientBuilder](https://github.com/Azure/autorest.csharp/blob/7ee8bdfee8e3cbb71b35b12d073e56f9561e5cb8/src/AutoRest.CSharp/Common/Output/Builders/ClientBuilder.cs#L138C1-L141C14), throws a fatal exception when processing any pageable method with more than one response that returns an object as its response body. This includes failure responses, which may return an object body to provide information about an error, but which should not arise as part of a paging flow without throwing a client exception already.

**Describe your ideas for solutions**

Current:
```
if (!(method.Responses.SingleOrDefault(r => r.ResponseBody != null)?.ResponseBody is ObjectResponseBody objectResponseBody))
```
Proposed:
```
if (!(method.Responses.SingleOrDefault(r => r.StatusCodes.Any(c => c.Family == 2) && r.ResponseBody != null)?.ResponseBody is ObjectResponseBody objectResponseBody))
```
(Or similar. Arguments could be made to include or exclude other status codes.)

**Existing workarounds**

Currently, users can avoid this issue by manually removing the content nodes for any failure responses that return an error object, or by applying a directive in their config to do the same.

**Downstream effects**

A majority of users currently affected by this restriction are either aware and using a workaround or are currently unable to generate a client for affected API specifications. Some minority of users may exist who are able to successfully generate a client for an API which is only pageable as part of an error response, but the generated client would then throw an error upon receiving a non-success status code for the paging request.

**Example affected specification node**

```
"get": {
  "responses": {
    "200": {
      "description": "Success",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/PaginatedResultDto[EntityDto]"
          }
        }
      }
    },
    "400": {
      "description": "Bad Request",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse"
          }
        }
      }
    }
  },
  "x-ms-pageable": {}
}
```

**Exception stack trace**

```
fatal   | System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable1 source, Func2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source, Func2 predicate)
   at AutoRest.CSharp.Common.Output.Builders.ClientBuilder.BuildPagingMethod(String methodName, String nextLinkName, String itemName, RestClientMethod method, RestClientMethod nextPageMethod, TypeDeclarationOptions declaration) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\ClientBuilder.cs:line 138
   at AutoRest.CSharp.Common.Output.Builders.ClientBuilder.BuildPagingMethods(InputClient inputClient, RestClient restClient, TypeDeclarationOptions declaration)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\ClientBuilder.cs:line 130
   at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.DataPlaneClient.getPagingMethods() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\Output\DataPlaneClient.cs:line 45
   at AutoRest.CSharp.Generation.Writers.DataPlaneClientWriter.WriteClient(CodeWriter writer, DataPlaneClient client, DataPlaneOutputLibrary library) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\Generation\DataPlaneClientWriter.cs:line 33
   at AutoRest.CSharp.AutoRest.Plugins.DataPlaneTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\AutoRest\DataPlaneTarget.cs:line 76
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(CodeModel codeModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 32
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 119
   at AutoRest.CSharp.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\PluginProcessor.cs:line 39
fatal   | Process() cancelled due to failure
error   |   Error: Plugin csharpgen reported failure.
```

**Comment by pshao25** [comment]
@a-ch-chu Please mark error response with `x-ms-error-response`
