### ISSUE TITLE
[DPG] Generation fails when using extended discriminated types as route responses

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4041]
Consider the following TypeSpec:

```text
@discriminator("type")
model DeletionStatus {
    type: string;
    deleted: boolean;
}

model AssistantFileDeletionStatus extends DeletionStatus {
  type: "assistant.file.deleted";
}

@delete
deleteAssistantFile(
    @path
    assistantId: string,

    @path
    fileId: string,
): AssistantFileDeletionStatus;
```

Notice how the extended discriminated type `AssistantFileDeletionStatus` is the response of the delete operation. This causes code generation to fail with the following error:

```text
{"level":"info","message":"dotnet --roll-forward Major E:/azure-sdk-for-net-pr/sdk/openai/Azure.AI.OpenAI.Assistants/TempTypeSpecFiles/OpenAI.Assistants/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path E:/azure-sdk-for-net-pr/sdk/openai/Azure.AI.OpenAI.Assistants/src   --clear-output-folder false"}
Unhandled exception. System.InvalidOperationException: Not implemented type: 'System.Object'
   at AutoRest.CSharp.Generation.Types.CSharpType.get_Implementation() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Types\CSharpType.cs:line 90
   at AutoRest.CSharp.Output.Models.Types.ObjectType.CreateExtraDescriptionWithDiscriminator() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 100
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_Description() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ObjectType.cs:line 47
   at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteObjectSchema(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 47
```

**Comment by ArcturusZhang** [comment]
Hi @joseharriaga using the tsp you provided here:
```
@discriminator("type")
model DeletionStatus {
    type: string;
    deleted: boolean;
}

model AssistantFileDeletionStatus extends DeletionStatus {
  type: "assistant.file.deleted";
}

@delete
op deleteAssistantFile(
    @path
    assistantId: string,

    @path
    fileId: string,
): AssistantFileDeletionStatus;
```

I can no longer reproduce your issue, the code is properly generated:
```csharp
        /// <param name="assistantId"> The <see cref="string"/> to use. </param>
        /// <param name="fileId"> The <see cref="string"/> to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="assistantId"/> or <paramref name="fileId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="assistantId"/> or <paramref name="fileId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <include file="Docs/ModelsTypeSpecClient.xml" path="doc/members/member[@name='DeleteAssistantFileAsync(string,string,CancellationToken)']/*" />
        public virtual async Task<Response<AssistantFileDeletionStatus>> DeleteAssistantFileAsync(string assistantId, string fileId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(assistantId, nameof(assistantId));
            Argument.AssertNotNullOrEmpty(fileId, nameof(fileId));

            RequestContext context = FromCancellationToken(cancellationToken);
            Response response = await DeleteAssistantFileAsync(assistantId, fileId, context).ConfigureAwait(false);
            return Response.FromValue(AssistantFileDeletionStatus.FromResponse(response), response);
        }

        /// <param name="assistantId"> The <see cref="string"/> to use. </param>
        /// <param name="fileId"> The <see cref="string"/> to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="assistantId"/> or <paramref name="fileId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="assistantId"/> or <paramref name="fileId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <include file="Docs/ModelsTypeSpecClient.xml" path="doc/members/member[@name='DeleteAssistantFile(string,string,CancellationToken)']/*" />
        public virtual Response<AssistantFileDeletionStatus> DeleteAssistantFile(string assistantId, string fileId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(assistantId, nameof(assistantId));
            Argument.AssertNotNullOrEmpty(fileId, nameof(fileId));

            RequestContext context = FromCancellationToken(cancellationToken);
            Response response = DeleteAssistantFile(assistantId, fileId, context);
            return Response.FromValue(AssistantFileDeletionStatus.FromResponse(response), response);
        }
```

therefore I believe this issue must have been fixed by our recent updates. Could you have a try again?
