### ISSUE TITLE
Import doesn't seem to be respected when generating from tsp

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4067]
I hit the below error when attempting to generate the Event Grid library. It seems to be related to the fact that the CommunicationIdentifierModel is defined in a separate imported tsp:

https://github.com/Azure/azure-rest-api-specs/blob/f03fab0589666c8bdccb0454673d77d3dd0d851e/specification/eventgrid/Azure.Messaging.EventGrid/AzureCommunicationServices.tsp#L1

https://github.com/Azure/azure-rest-api-specs/blob/f03fab0589666c8bdccb0454673d77d3dd0d851e/specification/eventgrid/Azure.Messaging.EventGrid/AzureCommunicationServicesCore.tsp#L2

https://github.com/Azure/azure-rest-api-specs/blob/f03fab0589666c8bdccb0454673d77d3dd0d851e/specification/eventgrid/Azure.Messaging.EventGrid/client.tsp#L5

This doesn't cause a problem when generating in the other languages.

To reproduce:

Check out https://github.com/JoshLove-msft/azure-sdk-for-net/tree/feature/eventgrid/namespaces

Run dotnet build /t:GenerateCode from sdk\eventgrid\Azure.Messaging.EventGrid.Namespaces directory.

```
{"level":"info","message":"dotnet --roll-forward Major C:/Users/jolov/repos/azure-sdk-for-net/sdk/eventgrid/Azure.Messaging.EventGrid.Namespaces/TempTypeSpecFiles/Azure.Messaging.EventGrid/node_modules/@autorest/csharp/AutoRest.CS 
  harp.dll --project-path C:/Users/jolov/repos/azure-sdk-for-net/sdk/eventgrid/Azure.Messaging.EventGrid.Namespaces/src   --clear-output-folder false"}
  Unhandled exception. System.NotSupportedException: No deserialization logic exists for CommunicationIdentifierModel
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.GetDeserializeImplementation(TypeProvider implementation, JsonElementExpression element, ValueExpression serializerOptions) in D:\a\_work\1\s\autorest.cs 
  harp\src\AutoRest.CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 773
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.GetDeserializeValueExpression(JsonElementExpression element, CSharpType serializationType, SerializationFormat serializationFormat, ValueExpression seria 
  lizerOptions) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 749
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.DeserializeValue(JsonSerialization serialization, JsonElementExpression element, ValueExpression& value) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.C 
  Sharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 675
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.DeserializeIntoObjectProperty(JsonPropertySerialization jsonPropertySerialization, JsonPropertyExpression jsonProperty, IReadOnlyDictionary`2 propertyVar 
  iables, Boolean shouldTreatEmptyStringAsNull) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 455
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.<>c__DisplayClass16_0.<DeserializeIntoObjectProperties>b__1(JsonPropertySerialization p) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Out 
  put\Builders\JsonSerializationMethodsBuilder.cs:line 433
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.DeserializeIntoObjectProperties(IEnumerable`1 propertySerializations, JsonPropertyExpression jsonProperty, IReadOnlyDictionary`2 propertyVariables, Boole 
  an shouldTreatEmptyStringAsNull) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 431
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.WriteObjectInitialization(JsonElementExpression element, JsonObjectSerialization serialization)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest 
  .CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 401
     at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.BuildDeserializeBody(Parameter element, JsonObjectSerialization serialization)+MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Ou 
  tput\Builders\JsonSerializationMethodsBuilder.cs:line 343
     at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Common.Output.Builders.JsonSerializationMethodsBuilder.BuildDeserialize(TypeDeclarationOptions declaration, JsonObjectSerialization serialization, INamedTypeSymbol existingType) in D:\a\_work\1\s\autorest.csh 
  arp\src\AutoRest.CSharp\Common\Output\Builders\JsonSerializationMethodsBuilder.cs:line 314
     at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteObjectSerialization(CodeWriter writer, SerializableObjectType model, TypeDeclarationOptions declaration, JsonObjectSerialization jsonSerialization, XmlObjectSeriali 
  zation xmlSerialization, Boolean isStruct, Boolean includeSerializer, Boolean includeDeserializer) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\SerializationWriter.cs:line 92
     at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteObjectSerialization(CodeWriter writer, SerializableObjectType model) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\SerializationWr 
  iter.cs:line 38
     at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteSerialization(CodeWriter writer, TypeProvider schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\SerializationWriter.cs:line 28 
     at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRes 
  t.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 32
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 83
     at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 51   
     at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
     at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
  --- End of stack trace from previous location ---
     at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
```

**Comment by JoshLove-msft** [comment]
The issue was that CommunicationIdentifierModel was not being added to the client.tsp despite the fact that AzureCommunicationServices was being added and it imported CommunicationIdentifierModel. Apparently all dependencies need to be explicitly added in client.tsp.
