### ISSUE TITLE
[DPG] Generation suddenly failing with NotSupportedException after Autorest update

### ISSUE THREAD

**Issue by m-redding** [Azure/autorest.csharp#4118]
One of the Autorest updates in the last 3 or 4 weeks no longer supports generation from the Schema Registry Typespec draft. I've been generating from this Typespec: https://github.com/Azure/azure-rest-api-specs/pull/25168 for a few months, with my last successful generation being on December 14th. After syncing my azure-sdk-for-net branch (see this PR: https://github.com/Azure/azure-sdk-for-net/pull/40639) to the latest commit, I can no longer generate from any versions of this Typespec. It fails with the following error: 

**`Unhandled exception. System.NotSupportedException: Content type application/json; serialization=Avro is not supported." `**

None of the other languages are having issues generating from the Typespec, and if I checkout a version of the repository from Mid-December (see: https://github.com/Azure/azure-sdk-for-net/pull/41145/files) I can successfully generate, so my assumption is that the issue is with Autorest and not the Typespec.

Here is the full error message from generating:

```
{"level":"info","message":"dotnet --roll-forward Major C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src   --clear-output-folder false"}
Unhandled exception. System.NotSupportedException: Content type application/json; serialization=Avro is not supported.
   at AutoRest.CSharp.Generation.Writers.FormattableStringHelpers.ToMediaType(String contentType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\FormattableStringHelpers.cs:line 184
   at AutoRest.CSharp.Generation.Writers.FormattableStringHelpers.GetConversionFromFrameworkToRequestContent(Parameter parameter, String contentType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\FormattableStringHelpers.cs:line 142
   at AutoRest.CSharp.Generation.Writers.FormattableStringHelpers.GetConversionFormattable(Parameter parameter, CSharpType toType, String contentType) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\FormattableStringHelpers.cs:line 103
   at AutoRest.CSharp.Output.Models.ConvenienceMethod.PrepareConvenienceMethodParameters(CodeWriterDeclaration contextVariable) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\ConvenienceMethod.cs:line 49
   at AutoRest.CSharp.Output.Models.ConvenienceMethod.GetParameterValues(CodeWriterDeclaration contextVariable) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Output\ConvenienceMethod.cs:line 22
   at AutoRest.CSharp.Generation.Writers.DpgClientWriter.WriteConvenienceMethod(LowLevelClientMethod clientMethod, ConvenienceMethod convenienceMethod, ClientFields fields, Boolean async) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\DpgClientWriter.cs:line 302
   at AutoRest.CSharp.Generation.Writers.DpgClientWriter.WriteConvenienceMethod(LowLevelClientMethod clientMethod, ConvenienceMethod convenienceMethod, OperationLongRunning longRunning, ProtocolMethodPaging pagingInfo, Boolean async) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\DpgClientWriter.cs:line 167
   at AutoRest.CSharp.Generation.Writers.DpgClientWriter.WriteClient() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\Generation\DpgClientWriter.cs:line 78
   at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 39
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 83
   at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 51
   at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
   at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
--- End of stack trace from previous location ---
   at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
   at AutoRest.CSharp.Program.<Main>(String[] args)
{"level":"info","message":"Command failed: dotnet --roll-forward Major C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src   --clear-output-folder false"}
Emitter "@azure-tools/typespec-csharp" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.csharp/issues
 
Error: Command failed: dotnet --roll-forward Major C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@autorest/csharp/AutoRest.CSharp.dll --project-path C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/src   --clear-output-folder false
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.$onEmit [as emitFunction] (file:///C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@azure-tools/typespec-csharp/dist/src/emitter.js:119:21)
    at async runEmitter (file:///C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@typespec/compiler/dist/src/core/program.js:556:13)
    at async compile (file:///C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@typespec/compiler/dist/src/core/program.js:242:9)
    at async compileOnce (file:///C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:37:25)
    at async compileAction (file:///C:/Users/mredding/source/repos/azure-sdk-for-net/sdk/schemaregistry/Azure.Data.SchemaRegistry/TempTypeSpecFiles/SchemaRegistry/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:21:9)
```

**Comment by pshao25** [comment]
It's known issue, could you provide more details of how you expect users send data with this content type?

**Comment by m-redding** [comment]
Is this a new change? I haven't had an issue with this before in either swagger or typespec. The Schema Registry Service accepts Avro schemas, so the user would be sending the actual Avro schema to the service as the request body to store in their registry. The service also returns Avro schemas in the response body when users retrieve their schemas.

**Comment by pshao25** [comment]
When user sets `application/json; serialization=Avro`, you expect the payload is bytes, right?

Your spec actually really confuses me:
1. A lot of get operations has specified the content type `ContentTypeEnum`, e.g., `getSchemaById`, `getSchemaByVersion`, etc. Why would get needs content types?
2. The only operation with content type that makes sense to me is `registerSchema`, which is defined equivalent to `op registerSchema(content: bytes, ...SchemaContentType)`. Your body is `bytes` but your `SchemaContentType` contains `application/json; serialization=Avro; application/json; serialization=json; text/plain; charset=utf-8`. I could understand the payload is a `BinaryData` if user sets `application/json; serialization=Avro;`, but what if `application/json; serialization=json`, still `BinaryData`?

**Comment by m-redding** [comment]
We expect the payload to be bytes, yes.
1. We need the content type enum so that we can determine the format of the schema, whether it is Avro, JSON, Protobuf, or custom, so that we can then return that format as part of the schema properties. It defines the set of possible content types and what format they map to. We always return the schema properties as part of those methods as the SchemaRegistrySchema.Properties value https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/schemaregistry/Azure.Data.SchemaRegistry/api/Azure.Data.SchemaRegistry.netstandard2.0.cs#L66 This design is necessary for our champion scenarios.
2. We always return schemas to the user as a string, so it works to just always receive the payload as BinaryData. If it's `application/json; serialization=json` it would be fine if it was treated as JSON but we don't need it, we just return it as a string anyway. Since we need BinaryData for Avro and it's fine for everything else then it simplifies it for us to just treat it as bytes.

**Comment by pshao25** [comment]
1. Sorry I just type it for wrong. What I'm asking is `SchemaContentTypeValues` inside `SchemaContentType`. My point is content type doesn't impact the deserialization at all. It shouldn't be in a get operation.
2. We could have a quick fix to unblock you but just serialize as bytes body no matter what content type is. But it is subject to change in the near future. We are going to change to "if user set binary content type, we serialize it as binary; if user set json content type, we serialize it as json".
