### ISSUE TITLE
[Microsoft Generator CSharp] Enable Extensible Metadata References from Assemblies

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4282]
Original discussion: https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/13#discussion_r1491801672.

As part of the [GeneratedWorkspace](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/AutoRest/Plugins/GeneratedCodeWorkspace.cs#L42) class, we reference several external azure types and their assemblies. These references should be made extensible, so an extending plugin can provide the types to reference and load as references.

**Comment by m-nash** [comment]
When we start this item lets have a quick sync to agree on design.

**Comment by jorgerangel-msft** [comment]
Did some local testing, the current implementation of adding metadata references will not work in a standalone exe app and leads to the following error:
```
System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.Generator.CSharp.GeneratedCodeWorkspace..cctor()
System.TypeInitializationException: The type initializer for 'Microsoft.Generator.CSharp.GeneratedCodeWorkspace' threw an exception.
 ---> System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.Generator.CSharp.GeneratedCodeWorkspace..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Generator.CSharp.GeneratedCodeWorkspace.Initialize()
   at Microsoft.Generator.CSharp.CSharpGen.ExecuteAsync(String outputPath, String configurationPath)
   at Microsoft.Generator.CSharp.Mgc.GeneratorRunner.RunAsync(CommandLineOptions options)
Error: The type initializer for 'Microsoft.Generator.CSharp.GeneratedCodeWorkspace' threw an exception.
```
