### ISSUE TITLE
System.InvalidOperationException: Can't find Baseline contract assembly

### ISSUE THREAD

**Issue by brrusino** [Azure/autorest.csharp#5176]
Seeing a failure for `SDK azure-sdk-for-net-track2` build step in azure-rest-api-specs PR build, but seems to be due to incorrect configuration somewhere:
```
03:02:31.663 cmderr 	[.Net] System.InvalidOperationException: Can't find Baseline contract assembly (Azure.ResourceManager.Chaos@1.0.0) from Nuget Global Package Folder at /home/cloudtest/.nuget/packages/azure.resourcemanager.chaos/1.0.0/lib/netstandard2.0/Azure.ResourceManager.Chaos.dll. Please make sure the baseline nuget package has been installed properly
03:02:31.663 cmderr 	[.Net]    at AutoRest.CSharp.Input.Source.SourceInputModel.LoadBaselineContract() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\Source\SourceInputModel.cs:line 164
03:02:31.664 cmderr 	[.Net]    at AutoRest.CSharp.Input.Source.SourceInputModel..ctor(Compilation customization, CompilationInput existingCompilation) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\Source\SourceInputModel.cs:line 32
03:02:31.664 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 84
03:02:31.664 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 62
03:02:31.664 cmderr 	[.Net]    at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
03:02:31.664 cmderr 	[.Net]    at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
03:02:31.664 cmderr 	[.Net] --- End of stack trace from previous location ---
03:02:31.665 cmderr 	[.Net]    at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
03:02:31.665 cmderr 	[.Net]    at AutoRest.CSharp.Program.<Main>(String[] args)
```

Verified that expected nuget package is available at Nuget.org and visually verified that our SDK shows this as the ApiCompat version (1.0.0).
https://www.nuget.org/packages/Azure.ResourceManager.Chaos
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/chaos/Azure.ResourceManager.Chaos/src/Azure.ResourceManager.Chaos.csproj

Is there something configured incorrectly? I would expect a breaking-change failure for our current PR for this build step, but not this specific failure.

Build link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4358104&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437

**Comment by live1206** [comment]
This should be a glitch in CI, Api Compat tool will download the previous GA .NET SDK.
And we can't simply ignore this failure, because it will ignore the Api Compat check failure.
We should have a better way to show the error message.
