### ISSUE TITLE
Using CodeGenSuppressAttribute breaks generator

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#601]
While trying to work around #600, I used the `CodeGenSuppressAttribute` which threw an exception:
```
  FATAL: System.InvalidOperationException: TypedConstant is not an array. Use Value property.
     at Microsoft.CodeAnalysis.TypedConstant.get_Values()
     at AutoRest.CSharp.V3.AutoRest.Plugins.MemberRemoverRewriter.GetSupressions(INamedTypeSymbol namedTypeSymbol) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\MemberRemoverRewriter.cs:line 69
     at AutoRest.CSharp.V3.AutoRest.Plugins.MemberRemoverRewriter.ShouldRemove(ISymbol symbol) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\MemberRemoverRewriter.cs:line 88
     at AutoRest.CSharp.V3.AutoRest.Plugins.MemberRemoverRewriter.VisitConstructorDeclaration(ConstructorDeclarationSyntax node) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\MemberRemoverRewriter.cs:line 32
     at Microsoft.CodeAnalysis.CSharp.Syntax.ConstructorDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
     at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclaationSyntax node)
     at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
     at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
     at AutoRest.CSharp.V3.AutoRest.Plugins.GeneratedCodeWorkspace.AddGeneratedFile(String name, String text) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\GeneratedCodeWorkspace.cs:line 42
     at AutoRest.CSharp.V3.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest, CodeModel codeModel, Configuration configuration) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\CSharpGen.cs:line 52
     at AutoRest.CSharp.V3.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in D:\a\1\s\src\AutoRest.CSharp.V3\AutoRest\Plugins\PluginProcessor.cs:line 54
```

I think this is because at https://github.com/Azure/autorest.csharp/blob/6aafd5a815c7646e22315af91b517bc4cbc58208/src/AutoRest.CSharp.V3/AutoRest/Plugins/MemberRemoverRewriter.cs#L69 you expect the `params` argument to have created an array, but at the time you're parsing this using Roslyn I don't believe that's true - they all look like arguments, this the line should probably be something like:

```csharp
var parameterTypes = attributeData.ConstructorArguments.Skip(1).Select(v => (ISymbol?)v.Value).ToArray();
```

**Comment by heaths** [comment]
This has been resolved.
