### ISSUE TITLE
Failed to install or start extension '@autorest/csharp-v3'

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/autorest.csharp#941]
I'm trying to move from the v2 generator to v3 by upgrading my swagger 2 API to OpenAPI 3 and using the new csharp generator. When doing the following:

```
autorest --csharp --v3 --input-file=v3.json --use:"https://github.com/Azure/autorest.csharp#feature/v3"
```

I get the following error:

```
AutoRest code generation utility [cli version: 3.0.6247; node: v14.15.0, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
   Installing AutoRest extension '@autorest/csharp-v3' (https://github.com/Azure/autorest.csharp#feature/v3)
Failed to install or start extension '@autorest/csharp-v3' (https://github.com/Azure/autorest.csharp#feature/v3)
  Error: Package '@autorest/csharp-v3' - '' failed to install:
  Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#3603e305a4456a442b2f886e1f58c4cf4fc59097' -- Error: Process Failed.Error: Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#3603e305a4456a442b2f886e1f58c4cf4fc59097' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async resolveExtensions (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\configuration.js:926:55)
    at async Configuration.CreateView (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\configuration.js:967:9)
    at async AutoRest.RegenerateView (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\autorest-core.js:66:29)
    at async currentMain (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:311:21)
    at async mainImpl (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:510:20)
    at async main (C:\Users\thoma\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:537:20)
```

As shown in the out I'm using node 14.15.0. Here's output from `autorest --info`:

```
AutoRest code generation utility [cli version: 3.0.6247; node: v14.15.0, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 extension  @autorest/azure-functions-csharp         0.2.0-preview-dev.321054549 C:\Users\thoma\.autorest\@autorest_azure-functions-csharp@0.2.0-preview-dev.321054549
 core       @autorest/core                           3.0.6320     C:\Users\thoma\.autorest\@autorest_core@3.0.6320
 extension  @autorest/modelerfour                    4.15.414     C:\Users\thoma\.autorest\@autorest_modelerfour@4.15.414
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\thoma\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\thoma\.autorest\@microsoft.azure_autorest.modeler@2.3.55
```

Do you know what could be wrong there?

**Comment by pakrym** [comment]
Currently, it's not possible to use V3 generator directly from the autorest command line. Please follow the guide from https://github.com/Azure/autorest.csharp#use-outside-of-the-azure-sdk-net-repo to try the V3 generator.

**Comment by ThomasArdal** [comment]
Are there any plans to support that without custom NuGet feeds etc.? Just trying to find out if AutoRest is evolving or pulled towards something that is used to build the Azure SDK only. I see that everything introduced as part of .NET 5 is using NSwag, why I'm trying to figure out if this is the way to go moving forward or if I can stick with AutoRest.

**Comment by pakrym** [comment]
Yes, that work is scheduled for the next month or so.

**Comment by ShivangiReja** [comment]
This feature it now enabled for V3 generator. Please refer these docs:
* https://github.com/Azure/autorest.csharp#default-autorest---csharp-generator-change
* https://github.com/Azure/autorest.csharp#use-outside-of-the-azure-sdk-net-repo
