### ISSUE TITLE
Generator throws exception on ACR swagger file

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#986]
### Description:

When I run generation on the [ACR Swagger file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/data-plane/Microsoft.ContainerRegistry/preview/2019-08-15/containerregistry.json) with `dotnet build /t:GenerateCode`, the following exception is thrown:

 FATAL: System.NotImplementedException: Form     at AutoRest.CSharp.Output.Builders.SerializationBuilder.BuildObject(KnownMediaType mediaType, ObjectSchema objectSchema, ObjectType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Builders\SerializationBuilder.cs:line 30
     at AutoRest.CSharp.Output.Models.Types.ObjectType.<BuildSerializations>b__63_0(KnownMediaType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 430
     at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at AutoRest.CSharp.Output.Models.Types.ObjectType.BuildSerializations() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 430
     at AutoRest.CSharp.Output.Models.Types.ObjectType.get_Serializations() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 85
     at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteObjectSerialization(CodeWriter writer, ObjectType model) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\SerializationWriter.cs:line 33
     at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteSerialization(CodeWriter writer, TypeProvider schema) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\SerializationWriter.cs:line 23
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 51
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 137
     at AutoRest.CSharp.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\PluginProcessor.cs:line 36

The full output is in this file: [acr-autorest-error.txt](https://github.com/Azure/autorest.csharp/files/5838887/acr-autorest-error.txt)

### Update:

The exception appears to be caused by something in the `/oauth2/exchange` and `/oauth2/token` POST operations.  Does the C# generator support the `application/x-www-form-urlencoded` content type?

**Comment by pakrym** [comment]
cc @chamons

**Comment by chamons** [comment]
Min repro case - https://gist.github.com/chamons/fe395252f960bee052bceef2615f6744

**Comment by chamons** [comment]
Removing these lines:
```
                    {
                        "$ref": "#/parameters/Grant_type"
                    }
```
Removes the exception. 

So does:
```
            "in": "formData",
```
to
```
            "in": "path",
```
The exception (with a small bit of pretty printing I added):
```
FATAL: System.NotImplementedException: BuildObject with Form from Paths108HwamOauth2ExchangePostRequestbodyContentApplicationXWwwFormUrlencodedSchema
   at AutoRest.CSharp.Output.Builders.SerializationBuilder.BuildObject(KnownMediaType mediaType, ObjectSchema objectSchema, ObjectType type) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Output\Builders\SerializationBuilder.cs:line 30
   at AutoRest.CSharp.Output.Models.Types.ObjectType.<BuildSerializations>b__63_0(KnownMediaType type) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 430
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.Types.ObjectType.BuildSerializations() in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 430
   at AutoRest.CSharp.Output.Models.Types.ObjectType.get_Serializations() in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Output\Models\Types\ObjectType.cs:line 85
   at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteObjectSerialization(CodeWriter writer, ObjectType model) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\SerializationWriter.cs:line 33
   at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteSerialization(CodeWriter writer, TypeProvider schema) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\Generation\Writers\SerializationWriter.cs:line 23
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 53
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\CSharpGen.cs:line 134
   at AutoRest.CSharp.AutoRest.Plugins.PluginProcessor.Start(IPluginCommunication autoRest) in C:\Users\chhamo\Programming\autorest.csharp\src\AutoRest.CSharp\AutoRest\Plugins\PluginProcessor.cs:line 36
  Error: Plugin csharpgen reported failure.
Invoke: C:\Users\chhamo\Programming\autorest.csharp\eng\Generation.psm1:36
```

[Code in question](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Output/Builders/SerializationBuilder.cs#L28)
